### ISSUE TITLE
New module xASR

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#106]
https://github.com/mgreenegit/xASR

**Comment by kwirkykat** [comment]
@mgreenegit I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) for submitting new resource modules to the DSC Resource Kit.

Can you please open a PR to a blank branch in your repo so that reviewers can make comments?

Some things you will need to fix in your repo:
- You need a Tests folder and an Examples folders in the root of your repository. (You can see an example of both these folders in the [xPSDesiredStateConfiguration repository](https://github.com/PowerShell/xPSDesiredStateConfiguration).)
- There seem to be a couple loose resource/helper files in the root of your repository. Those will need to go in the DSCResources folder.

**Comment by johlju** [comment]
Are there still interest of adding the xASR resource module to the DSC Resource Kit?
If so I like to help getting this reviewed according to the new process of getting a resource module added to the DSC Resource Kit.
I have opened an issue to update the text on [How to do a new resource module submission](https://github.com/PowerShell/DscResources/issues/356),
but basically if we gonna submit this resource module to DSC Resource Kit we need to make sure it follows the [Quality Governance](https://github.com/PowerShell/DscResources/blob/master/Naming.md#quality-governance).
