### ISSUE TITLE
Question on variable naming convention

### ISSUE THREAD

**Issue by megamorf** [PowerShell/DscResources#109]
Hey guys, 

The DSC resource [style guide](https://github.com/PowerShell/DscResources/blob/0a9d28fcc467dfe7609d29ad7122f3d2dd2b4586/StyleGuidelines.md) dictates that camel case notation should be used for variable names. 

I've had a small back and forth with @NarineM about that in the xPSDesiredStateConfiguration repo ([PR90](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/90)).

I understand that camel case notation is best practice in the .NET world but in PowerShell code parameters commonly dictate the variable naming convention, i.e. pascal case. I have had a look at the official PowerShell best practices on msdn and couldn't find anything on using camel case for variables. On the other hand they only mention pascal case in conjunction with function names explicitly. 

My history with PowerShell dates back almost to PSv1 and from what I've seen over the years pascal case for variable names is the established best practice and works well with pascal case parameter names.

Could you explain your reasoning behind this decision?

Thanks in advance :-)

- Sebastian

**Comment by KarolKaczmarek** [comment]
Hi @megamorf ,

Thanks for you input. We are indeed [recommending pascal case for parameter names](https://github.com/PowerShell/DscResources/blob/0a9d28fcc467dfe7609d29ad7122f3d2dd2b4586/StyleGuidelines.md#parameter-names-should-use-pascalcase-). There's no official PowerShell recommendation on that for local variables, however I've seen both pascal and camel case used for those. More important than what choice we make however is to use consistent convention for all DscResource modules. We decided to go with camel case since that was what majority of the initial modules were using and that's also convention used in pester. That's not saying one way is better than another, as it's just a matter of preference, but for consistency we had to choose one convention. 

Karol

**Comment by kwirkykat** [comment]
We updated the DSC Resource Kit [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) last week.

As @KarolKaczmarek stated before, the number 1 reason we dictate camelCase for variables is consistency.

The number 2 reason we do it is for clarity.

We use PascalCase for parameters to make it clear where the values for those variables are coming from. PascalCase is also used for function names so it's easy to remember that the variables in PascalCase go with the function. These parameters will also be in PascalCase when you call the function.

We use camelCase for all other variables to differentiate from parameters.
In addition, variables with a special scope (script, global, env) must specify that scope every time they are called to make it clear that they are not standard variables.

I'm not sure what happened in [PR90](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/90), but I hope that answered your question and gave you some clarity.
