### ISSUE TITLE
Add PR/Issue template for all DSC Repositories

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#112]
Many PR's submitted to the DSC Repos are often missing one or more of the key items covered in the [DSC Contribution Guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md). This might head off a few "can you please fix" responses (I'm guilty of missing some of these myself).

Could we perhaps create a default PR text (by creating a PULL_REQUEST_TEMPLATE.md in the .github folder in the repo root) that contains a checklist of items that a PR should contain? Each item could contain links to the relevant information on how to resolve/check.

For example:
- [ ] Change details added to Unreleased section of readme.md?
- [ ] Readme.md updated with details of new/changed resource, including samples and resource parameter details?
- [ ] Samples created/updated in Samples folder?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) run?
- [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Is this something that might be useful?

**Comment by KarolKaczmarek** [comment]
I think it may be worth trying, perhaps for 1 or 2 repos first and if we find it's helpful we could apply it to other repos.
@TravisEz13 @tysonjhayes @BrianFarnhill thoughts?

**Comment by tysonjhayes** [comment]
Sounds like a good idea to me, I'm fine with using xNetworking or xWebAdministration as some proof of concept repos.

We'd probably should look into [Pull Request Templates](https://github.com/blog/2111-issue-and-pull-request-templates) which seem to be doing what we're looking for.

**Comment by tysonjhayes** [comment]
In fact we should probably look into all of those templates, as they all seem pretty useful.

**Comment by BrianFarnhill** [comment]
I'm open to giving it a go - I like some of those other templates there as well like @tysonjhayes said. I'll put these in to xSharePoint and see what our contributors make of it as a test if that works? We generally see 15-20 pull requests a month so that should be a decent enough test run if we do it for a month and collect some feedback from there. Thoughts?

**Comment by PlagueHO** [comment]
@tysonjhayes @BrianFarnhill @tysonjhayes  - The Issue template would definitely help too - perhaps could provide an easy way to prompt the user to categorize the issue (Enhancement, New Resource Request, Bug report).

xNetworking is pretty quiet on the PR/Issue front at the moment so xWebAdministration and/or xSharePoint might be a better test.

**Comment by KarolKaczmarek** [comment]
@BrianFarnhill Sure, go for it 👍

**Comment by PlagueHO** [comment]
@BrianFarnhill, @KarolKaczmarek, @tysonjhayes - I'll get this kicked off by submitting a proposed PR and Issue template to the xWebAdministration repo then. Everyone can then refine the PR over there.

**Comment by PlagueHO** [comment]
Sorry, I opened the issue in the xWebAdministration repo. Have closed it and opened it in xSharePoint now.

**Comment by PlagueHO** [comment]
@BrianFarnhill, @KarolKaczmarek , @tysonjhayes, @TravisEz13: I've submitted the PR for this . It will most likely need a lot of tweaking, so please feel free to hammer it suggestions!

**Comment by BrianFarnhill** [comment]
@PlagueHO Just kicked off our review process on it, thanks for pushing this starting point in!

**Comment by PlagueHO** [comment]
@BrianFarnhill - Nice! Thank you - I'll get to work on your changes.

**Comment by KarolKaczmarek** [comment]
let's leave this issue open until we finish testing it under xSharePoint (https://github.com/PowerShell/xSharePoint/pull/264 ) and eventually adopt for all repos

**Comment by BrianFarnhill** [comment]
Some initial feedback as a repo owner on the first couple of issues that are coming through with the template:

 - Seeing the template in full when someone submits something makes it super hard to read (see [this issue](https://github.com/PowerShell/xSharePoint/issues/275) for an example)
 - In another case the issue was typed above the template and the template submitted below it
 - One other case saw the template deleted and ignored all together

Now I'm not super upset by people not using the template all the time because I accept that it's something that it ultimately beyond our control, so the first issue on that list is the one that is troubling me the most. Do we need to make is clear to remove some parts of the text or something like that as a starting point? What about educating people on how the check boxes work in terms of markdown syntax? and then adding more text to each point because putting it on the end of the line after the question is still hard to read as well.

That's just some initial thoughts - will give it some more time but would like to hear what you guys think in that regard?

**Comment by KarolKaczmarek** [comment]
I think the problem here is that current template leaves too much for contributor's own interpretation.
They can just read the checklist, remove it and type their details while having the checklist in mind (or not). Some people will add description below the template, some above and others (like in the linked example) next to the checklist while answering every question or marking the checkbox.

Checklist may be good option for PR template, but for issues perhaps better approach would be to modify it so that it acts more as a set of headers (questions) with room below to provide answer (or N/A if not applicable?).
We could format those headers to make them bold which would improve readability and make our comments italic to easily differentiate them from contributor's comments.

So, e.g. something like:



_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

**Details of the scenario you try and problem that is occurring:**


**The DSC configuration that is using the resource:**


**Version of the Operating System and PowerShell the DSC Target Node is running:**


**Version of the DSC module you're using:** 


_Your feedback and support is greatly appreciated._

_If you are able to resolve this issue or add new features, you may submit a Pull Request against this project. Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

What do you think?

**Comment by PlagueHO** [comment]
@BrianFarnhill  - great feedback. @KarolKaczmarek  - that looks pretty good to me. I'll submit the PR and if Brian has any suggestions we can make it to that.

**Comment by BrianFarnhill** [comment]
Happy with those changes, they are now merged in and we'll see how they go. Thanks guys

**Comment by PlagueHO** [comment]
I'm closing this one now as most repos have now implemented this.
