### ISSUE TITLE
Test templates versioning

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/DscResources#124]
Sometimes we update/fix a bug in a template without updating modules which used the old templates (example: https://github.com/PowerShell/DscResources/issues/122) .
This creates some management problem with figuring out what version each test is using.

This was already proposed previously, but we didn't have anyone pushing it forward, so wanted to discuss it again. Should we add header with the version number to the template which would be increased each time we will update the template? We could you sem ver for that to mark significance of the changes as well.

The template used in the specific repo may be modified separately, so version wouldn't necessarily guarantee what code is there, but at least we could easily figure out which tests will potentially need to be updated when the template is modified, so I think that may be useful.

Looking for your feedback on whether you think we should version test templates or not.

**Comment by PlagueHO** [comment]
@KarolKaczmarek  - I 100% agree. I think one of the early versions of the Test.Templates did include a version number but at the time we all hoped it wasn't necessary so it was removed. Easy to add back - I'll submit a PR.

I'd also suggest a simple changelist.md file added to the Test.Templates as well - just so that if the version number does have to change, everyone is aware of what the change was. Is that worth implementing?

**Comment by KarolKaczmarek** [comment]
sounds good to me
