### ISSUE TITLE
Community Call Comments, Questions, and Feedback (August 3)

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/DscResources#168]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on August 3 1-2PM PDT.

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/08-03-16/Agenda.md).

**Comment by gordonbondon** [comment]
Voting on most requested modules was briefly discussed at the end of the call.
 Maybe it will be useful to create a trello board like it was done by sqlps team ([link](https://trello.com/b/NEerYXUU/powershell-sql-client-tools-sqlps-ssms))? Seems it was really successful for them.

**Comment by kilasuit** [comment]
@kwirkykat could we get the list of blocked DSCResources that was mentioned in the call - I'll try and put some time aside for working on them where possible.

Also is it possible for the Skype Conversation transcript for this call & the previous call to be uploaded as well as there were some links shared through out the call

**Comment by kwirkykat** [comment]
@kilasuit Yes I can post the transcripts as well.
Formatting the notes now so that I can post them...
Here's the list of blocked modules in advance:
    - xAzure
    - xAzurePack
    - xJea
    - xMySql
    - xRemoteDesktopAdmin
    - xSafeHarbor
    - xSCDPM
    - xSCSMA
    - xSCSR
    - xSCOM
    - xSCSR
    - xSCOM
    - xSCSPF
    - xSCVMM
    - xWebDeploy
    - xWordPress

**Comment by johlju** [comment]
Sadly I couldn't attend the call this time, but listening back now. 

@kwirkykat You mention in the call you guys felt bad about commenting on style when you review PR's. I would say, don't feel that, it's important that style adhere to the guidelines. And I think all contributors understand the importance and are happy to change any style issues. Even after the "automatic style corrector" are ran in the future we could potentially have style issues. 
Myself are impressed when you find tiny misspellings in comments or a white space that got in where it shouldn't :) Each comment makes me a better coder!

**Comment by PlagueHO** [comment]
@Johlju - I completely agree.

Although it definitely is hard to not feel a little bit bad - especially if it is someone's first PR's into the community. I also worry that I'll put someone off contributing further by repeating "please use named parameters" or "Can you split this line please" 50 times in a PR :smile: . Still, being able to learn quickly to adapt to coding guidelines does help make good programmers.

**Comment by johlju** [comment]
@PlagueHO - I understand. :D

Maybe we should just do one comment, like "We need to split this line, and could you do the same throughout the rest of the code?". And finalize with comment "We review again when you commit these changes". And when the commit comes, reviewer reviews from the beginning again. 

I think the biggest problem with the review process is Reviewable which isn't easy for beginners. I know! I'm still afraid I click somewhere that I shouldn't. It's a lot of "buttons" that light up now and then. But then I think, if I mess up, someone else will help me out and correct it. :)
That said I think reviewable is an awesome tool, and I really like it, even liked it when I didn't know how to use it, because how it looked.
Learned that pressing 'h' in Reviewable literally helps! :) But sometimes the help notes that popup are not very helpful for beginners like my self. But it's fun to learn! :)

**Comment by athaynes** [comment]
IMO as a new contributor still learning the process, I think it is important to understand the community I am joining. I work with a lot of people who operate under the, if the script works it is right mantra. That might be fine for someone who doesn't share their automation, but not so much for a community project. Transitioning from an admin to a dev or at least sitting in the middle requires additional skillsets to be developed. If I am learning new skills, then getting started with good habits is a bonus to being part of a community. 

Also not having style guidelines seems to be like reading a paper with the font constantly changing. The info is there, but man it makes my brain hurt :)

**Comment by PlagueHO** [comment]
@johlju - Oh yes, reviewable.io - one awesome tool but completely overwhelming at first. Certainly daunting if you're only new to the whole PR/Review process.

@athaynes - I think everyone does their best to try to be as nice as possible when reviewing, because we know how easy it is to make mistakes. I like to point out to people that no matter how long you've been doing this for, you still make heaps of mistakes - I certainly do (as I'm sure anyone in the PS team reviewing my DSC resource submissions will attest to :smile:). That's the point of reviews right?

Anyway, perhaps it might be worth putting some sort of "Guide for first time submitters". Let them know what to expect and that it's to be expected that there are usually a few "fixed" required. I reckon there are probably submitters out there who get scared off by any review comments and so either never submit again or even leave PR's in an incomplete state so they have to be eventually deleted (there were a couple in xNetworking I can remember).

I wrote a blog series a while back on how to get started contributing to the DSC community. Perhaps I should extend it with some details on the review process and what to expect?
