### ISSUE TITLE
Add example showing how to access script variables inside InModuleScope

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#173]
When the test templates were changed to declare some of the resource variables as `$script:` scope, this prevented these variables from being accessed from within InModuleScope blocks.

InModuleScope blocks will not be used for public functions (*-TargetResource), but are still used for private functions.

There is an way to redeclare a variable declared outside a InModuleScope block so that it can be used inside the block:

``` powershell
InModuleScope $script:DSCResourceName {
    $script:DSCResourceName = (Get-Variable -Name 'DSCResourceName').Value
    # Do some tests
}
```

This needs to be added as an example in TestGuidelines.md.

I'll submit a PR.

**Comment by PlagueHO** [comment]
Unfortunately the above suggestion does not work.

Also, see this discussion:

https://github.com/pester/Pester/issues/342

We might just have to redeclare any variables needed in the InModuleScope for private functions. This is a bit messy though and feels like the wrong thing to do.

Any suggestions from you smarter people?

**Comment by kwirkykat** [comment]
@PlagueHO Yes, this is a problem.
There are two solutions I see on the table right now:
1. Don't use the script variables inside InModuleScope. You can re-declare them inside the scope without the script prefix if need be.
2. Switch the script variables back to globals.

I'm leaning towards 1 because globals get defined *everywhere* and hence could screw up other tests or the module. Though I can see how 1 isn't as clean code-wise.

@mbreakey3 I know you've been working a lot with #169. What do you think?

**Comment by mbreakey3** [comment]
For now, I agree with you that 1 is the better of the two options. When possible, InModuleScope should only surround the testing of non-exported functions though, which should help. Once the new version of Pester comes out that's supposed to support nested Describe blocks that will be even better, because we can replace InModuleScope with a Describe block instead

**Comment by PlagueHO** [comment]
I'll close this one until after the new version of Pester is released that will improve the InModuleScope situation.

**Comment by PlagueHO** [comment]
I've reopened this issue because @narrieta submitted some new tests to xNetworking in [this PR](https://github.com/PowerShell/xNetworking/pull/147). The tests solved some of the problems that I encountered when removing InModuleScope, so I'll submit a PR to add an example to TestGuidelines.md of what he did.
