### ISSUE TITLE
Guidance on how to document breaking changes is missing

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#178]
When code changes need to be made that breaks previous functionality, like changing a key in the schema. How should we make the users aware of the breaking change? And how long should one wait for getting feedback from the community (on the submitted issue) for such a change before implementing it? 

In the xSQLServer resource we need to make adjustments to the schema in a few resources, which all will be a breaking change. One of these are already merged. _I'm happy to fix any improvements in that resource to whatever comes out of this discussion._
In the README.md under the unreleased section for the xSQLServerLogin resource is says the following.
* Changes to xSQLServerLogin
 - Fixed an issue where it was not possible to add the same login to two instances on the same server.

It's not clearly stated that this is a breaking change. 

For the PR PowerShell/xSQLServer#64 there is a issue PowerShell/xSQLServer#117 which was tagged with `Breaking change`. Maybe we can document these issues, with the tag `breaking change`, differently in the README.md. In that case we should also make sure that tag is set on all those kind of issues (maybe change Maintainers.md to reflect that).

I write this because I have not seen this being documented specially in other resources either (I might have missed it). So maybe this has not been an issue before, or maybe the need to document this in any special way is not necessary.

**Comment by PlagueHO** [comment]
I'm proposing a breaking change to one of the xStorage resources at the moment, so have the same questions.

As DSC resources are all using SemVer, should we always ensure that a breaking change triggers an increase it the Major version number (e.g. 2.0.0.0->3.0.0.0)?

**Comment by kwirkykat** [comment]
@johlju @PlagueHO I just added the ```breaking change``` label to all the repositories (except SharePointDsc because I think Brian has his own system). Issues and PRs that include breaking changes should include this label.

It's also *extremely* helpful for maintainers, contributors, and users if some indication of the breaking change is included in the release notes and the title of the PR (the titles of merged PRs are actually the first thing I look at for releases).

The versioning currently works like this:
* Modules that still have the x... naming are incremented by a full version number if there is a breaking change (2.2.0.0 --> 3.0.0.0). All of these modules are still considered to be in 'preview' or 'experimental' mode.
* Modules that have the ...Dsc naming but are still in the 'preview' phase (prior to 1.0.0.0) are incremented only by a sub-version until they are ready to come out of preview (0.3.0.0 --> 0.4.0.0).
* Modules that have the ...Dsc naming and are out of the 'preview' phase (1.0.0.0 and after) are incremented by a full version number (2.2.0.0 --> 3.0.0.0).

I can update both the maintainers doc and the contributors doc with this info.

**Comment by kwirkykat** [comment]
@johlju @PlagueHO I added a ['Breaking Changes' section](https://github.com/PowerShell/DscResources/blob/master/Maintainers.md#breaking-changes) to Maintainers.md. I can add a section on breaking changes to the contributors guide as well after #177 is merged.

**Comment by kwirkykat** [comment]
@johlju @PlagueHO Nevermind. #177 deals with a separate document. I added a [Breaking Changes section](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#breaking-changes) to Contributing.md as well.
