### ISSUE TITLE
Using the Script resource - Is this the right way to use DSC?

### ISSUE THREAD

**Issue by jachin84** [PowerShell/DscResources#186]
This is more of a discussion point rather than an issue. I've recently converted a number of internal PowerShell scripts, used to configure our base server image, over to PowerShell DSC. I use the scripts to install certificates, disable insecure Cipher suites, configure remote desktop, install support tools and a number of other standard tweaks and security settings. As a regular PowerShell script this is easy, execute a process or WMI method, add a registry key, run an installer, etc. Using PowerShell DSC I've struggled and found that many of the built-in or community resources where not quite a good fit for my situation. As a result I've found that most of my PowerShell DSC configuration is comprised of the Script resource. In practice this results in a huge DSC configuration as a few lines form a script equate to many lines in the GetScript, TestScript, SetScript blocks of the Script resource. 

It was not an easy exercise to do the conversion and after completing the work I was left with the nagging question, "Is this really the way to do it?"

Is anyone else finding that their configurations rely heavily on the Script resource or are you authoring your own DSC Resource to suit your particular circumstance? 

Here are some examples of the things I had to use the Script resource to configure as I couldn't find a built-in/community resource:
- Managing Windows Credential store.
- Executing a WMI Method.
- Mapping a network drive.
- Adding a large number of registry keys - This wouldn't be an issue if the built in resource allowed specifying an array of Key, ValueName, ValueData.
- Executing an arbitrary process 
- Install Non-MSI software - I know there is the Package resource but it would be better to have an arbitrary test instead of the ProductionID.

What has your experience been?

**Comment by PlagueHO** [comment]
Hi @jachin84 - I can definitely relate to this:
We are also deploying and configuring more and more complex workloads with DSC. This I think is a reflection of our growing trust and understanding in the technology. But we do run into the same problem with these more complex workloads: no available resource to configure a specific item.

When we run across this we have several solutions available:
1. Use xScript.
2. Find a 'c' community resource that can do the job.
3. Create our own Resource Module to configure the item.
4. Raise an issue in a related module to get a new Resource added or raise an issue in DSCResources to get a completely new Resource Module created.
5. Identify a different method of applying the workload (there sometimes is multiple ways to configure the same thing - e.g. the File resource could be used to remove Certificates from the Windows certificate store).

IMHO, option 4 is definitely the way to go. The first thing we do when we hit a need that isn't covered by existing resource is raise an issue in the appropriate repo to see if someone has a solution or a resource they've been sitting on and want to get added. More often than many people have the same need.

People sometimes also have resources lying around that they created internally that they might be willing to share/submit to the resource kit if they know someone could use it.

Failing that many people in the DSC community are willing to help either extend the features of existing resources or create them from scratch if they see a few people asking for it. I try to add new resources and address issues whenever I can (as do many other people). It can take a bit of time for new features to be added or resources to be created (depending on the resource) - so while you're waiting you can continue to use xScript. This is what we do.

Looking at the list of items you've specified, they're all definitely things that could be either implemented as new resources or existing resources extended. So I'd definitely recommend going and logging them with the appropriate repo.

Anyway that is my 2c. Hope it helps :smile:

**Comment by ArieHein** [comment]
I think it boils down to what DSC was meant to do and what you want it to do. For example, why would you use DSC for mapping network drives ?

As i see it, DSC is mainly for Server operations, not User or Interactive operations. True you can install software as part of a Server configuration but you can still use UNC path as the source (if that was the reason for Mapping in the first place).

Executing WMI methods is in an interesting usage, if you can elaborate a bit more. I cant remember a time i needed to use WMI for Server state. On a general note, DSC isn't working well with logic or orchestration inside the DSC, this should be done outside of it, which leads to multiple dsc scripts per situation and multiple mof files but that's how the tool was originally meant to be used, imho. You can do some clever "tricks" with ConfigurationNames and Partial Configurations to achieve most of the scenarios. But interested to hear more :)

The multiple registry settings and Array support is indeed an issue i have causing large scripts but i can understand why its not an array or why using an array would be problematic and that's the Idempotent state. If you think of every single registry as one atomic unit of execution like a database transaction, If setting one registry setting fails, i can ty again . If the setting value changes, later on, i can fix it.

 If i have an array of registry settings, what happens if somewhere in the middle of that array, i have an issue setting the value...what happens to all the registry keys i set before that...do i roll them back ? do i ignore the fault and continue to the next registry ?  What if there are multiple errors along the array ? how will i then check that the state of all the keys are as i wanted them to be ?
I'm still pondering at my spare time better ways to do it, but i think some of those registry keys will go back to GroupPolicy, especially ones that have to be done as a full group of changes , either all of them are changed or none.

**Comment by Justin-DynamicD** [comment]
Most have answered this but one area a bit glossed over:  you mentioned the extra overhead in writing a get/test/set version of the script.  I recommend you look at some of the existing modules,  as people have had some clever work around for that.

Mostly around the set and test,  there tends to be a LOT of duplicated logic so you can usually get away with making one "helper function" to act as your main code,  then have both the test- and get- functions merely splat into that (with one having one extra switch parameter so it only tests and returns true/false vs making changes).  It can cut down on your duplication work dramatically and keep you from feeling like you're developing 3 scripts vs one:  keep making that one script, then just "present" two different return formats depending on what DSC function calls it.

Outside that, the big thing to remember with DSC is it's really not designed to be used to create dynamic configurations.  It's really about taking dynamic parameters and building a _static_ configurations file then enforcing/reporting on them.  That resulting mof is fixed, so any attempts to do things like "map drive s: when joe logs in" isn't going to work.  All those IFs have to be hashed out during the mof compile.  It's not a "bad" thing,  it just means that DSC has a very targeted, specific purpose.  Think of them as server templates.  "All my Hyper-V hosts should look like this".  That's all static settings than can be determined during compile.  Not "John's profile should look like this no matter where he logs in".   Those settings aren't static to the machine, they are conditional to who logs in and thus .... no good.

**Comment by johlju** [comment]
I assume this issue has been resolved. If this was closed in error, please comment and reopen.
