### ISSUE TITLE
Discussion: Reviewable.IO or the new GitHub Code Review?

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#193]
Now that GitHub has provided a much better [pull request code review experience](https://github.com/universe-2016#reviews) and feature list is it worth making it an option to use (as opposed to Reviewable).

Personally I really love the features in Reviewable but it has some issues:
1. It can be pretty overwhelming for newcomers.
2. Reviewing larger changes can really cripple your browser.

Has anyone performed a large code review using the new GitHub Code Review feature? Does it have performance issues?

Just thought this might be worth discussing.

**Comment by Dan1el42** [comment]
I think going back to GitHub's native now improved code review system would open the opportunity to create an extension for Visual Studio Code to facilitate the review in a full-featured editor. GitHub provides an API to create a comment on a line of code in a PR or reply to it which we could leverage.

**Comment by KarolKaczmarek** [comment]
The biggest advantage of reviewable for me is support for iterations... I don't see it implemented in the new GitHub code review system, but didn't play with it a lot, so I may be missing it.

**Comment by BrianFarnhill** [comment]
Yea I've done some monster code reviews with reviewable and had my browser crash a fair bit because of it (that said it's getting better at recognising that itself and showing fewer files), but I'm with @KarolKaczmarek on this one, until there is the ability to review a file with its revisions I wouldn't be super keen to switch.

That said, to @Dan1el42 's idea - if GitHub/anyone writes an extension for any code review platform that integrates in to VS Code, then they can shut up and take my money because I'll jump ship to that as soon as it's a thing :P

**Comment by PlagueHO** [comment]
Lol @BrianFarnhill - so now I know what my get rich quick scheme should be :smile: 

I haven't actually tried out a "real life" code review using the new GitHub tools. But as @KarolKaczmarek says if it doesn't support iterations yet then it is missing an important function. I might try out a small review on something when I get a chance. Good to get everyone's thoughts on this! Thanks @Dan1el42

**Comment by johlju** [comment]
Even if there are options to "Show changes since your last review" or <kbd>shift</kbd>+click on a range of commits it is still for the entire PR, there are missing granular control.

My personal opinion is that Reviewable is by far better. Reviewable is going through a total rewrite and is slowly be release to the masses according to Twitter, so hopefully it will be better equipped to handle our loads. But honestly I have never had a big problem with Reviewable, and when I found a minor problem it has been fixed within days, if not hours.

By all comments it seems all are in favor of Reviewable, so I suggest we close this issue.

**Comment by PlagueHO** [comment]
@johlju - after a year or two to think it over and kick the tires of the GH review process I always end up going to Reviewable. So I'm still well in favor of Reviewable - just wanted to pose the question. So I think I should close this. Can still be reopened if there are more comments.
