### ISSUE TITLE
How should we use and document unused non-mandatory parameter in the Get-method of a resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#206]
I came across two different scenarios when unused non-mandatory parameters are used in the Get-method in my recent reviews.
What I mean with 'unused' is that they are no used for any validation or assignment in the Get-method (other than the returned hastable), but rather to be able to call Get-method using `Get-TargetResource @PSBoundParameter`.

In PR PowerShell/xSQLServer#147 the non-mandatory parameters are not used to determine outcome. And the paramater variable are later re-assigned to the value of the actual state, so the value provided by the user in the function call is never used in the returned hash table anyway.

Also, if allowing unused non-mandatory parameters in the Get-method and also using them in the returned hash table, do we not open up for potential giving false information to the user when calling the `Get-DscConfiguration`? We are returning the state the user wants for that parameter, not the actual state.

And in tests this would add more test code which gives even more complexity.

In PR PowerShell/xSQLServer#147 this could be the exception to the "rule". They are also added so the Get-method can be called using `Get-TargetResource @PSBoundParameter`.
But the two parameters in question (`RestartService` and `RestartTimeout`) does actually provide the user with relevant information which would be of interest for the user when calling `Get-DscConfiguration`.
In this PR @mbreakey3 asked to get comments on the unused parameters in the comment-based help. 
So there is a comment that says 

```
.PARAMETER RestartTimeout
*** Not used in this function ***
The length of time, in seconds, to wait for the service to restart. 
```

But that is not entirely true either since it is relevant information, and it is used in the returned hash table.

Anyway. So if we do allow unused non-mandatory parameters I think we need to add the approach that @mbreakey3 took above into the style guideline, or best practices guideline.

If I could choose I would like to _not_ allow unused parameters, but do allow the exceptions to the rule. :smile:

Just my thoughts. Happy to go either way.

**Comment by kwirkykat** [comment]
@johlju  @mbreakey3 and I were discussing this the other day (probably because she was talking to you about it :slightly_smiling_face:). In PSDscResources we did not include the unused non-mandatory parameters from Get-TargetResource because these properties are retrieved from the actual resource.

I see the inclusion of the non-mandatory parameters as a signal that there is a design flaw in the implementation of Get-TargetResource because this function should retrieve the actual values of the properties for that resource. For example, if there is a parameter FilePathName that can be set but is not mandatory, and Get-TargetResource should return the actual set value of FilePathName for that resource, so passing in a FilePathName parameter would be extremely confusing.

I do see the case where including a non-mandatory parameter would be tempting for a property that *cannot* be retrieved from the resource or is only used within the Test/Set functions, and I'm completely willing to hear a good argument from the opposing viewpoint, but I am currently set firmly in the camp of "No non-mandatory parameters in Get-TargetResource" (except perhaps parameters about logging the operation).

There are cases where *mandatory* parameters pop up in Get-TargetResource that aren't used (Ensure mostly). And in this case a simple "Not used in Get-TargetResource" in the parameter comment like in your example above should be included.

**Comment by BrianFarnhill** [comment]
In SharePointDsc we have included all the non-mandatory properties in the get method in every single resource, and that was to simplify how we can call the get method from the test and set methods. We call the get method in the test method to determine the current values and return true/false from there, and we call it form the set method to understand the changes that need to be made to get from current state to desired state. So it's been easier to just call "Get-TargetResource @PSBoundParameters" in all places to get the values back out. That said, we could change this to be specific for each individual resource to pass just the required values, but it is kinda clean the way it is for us. Worth considering that approach as well in the context of this conversation.

**Comment by johlju** [comment]
I would rather see that unused parameters should be avoided in the Get-method as much as possible. We could allow module specific guidelines, per DSC module, to override this.

@kwirkykat Shall I try to write something up regarding this? If so, I try to incorporate this into the the StyleGuidelines under the Best Practice section.

To summarize:
* Get-TargetResource should not contain unused _non-mandatory_ parameters.
* Get-TargetResource with unused _mandatory_ parameters should include "Not used in Get-TargetResource" in the parameter description (in the comment-based help).

**Comment by kwirkykat** [comment]
@johlju @BrianFarnhill  This is a lot like #209 for me. If it's already in clean, working code, you don't need to change it.

But for new people/resources just getting started or still updating to HQRM, this would probably be good to have in Best Practices. But it should go in the BestPractices.md document and not the Best Practices section of the Style Guidelines (which is being moved to the other document)

**Comment by johlju** [comment]
Proposal in PR #229
