### ISSUE TITLE
New Resource Module: DockerDsc

### ISSUE THREAD

**Issue by bgelens** [PowerShell/DscResources#208]
Class based DSC resource module to deal with Docker managed Container Hosts.
For now it only contains 1 resource: DockerService to install or remove the docker service from windows.
I want to figure out what needs to be done to have a Class based module added to the DSCReskit so help on unit tests for example is more then welcome!
https://github.com/bgelens/DockerDsc

**Comment by PlagueHO** [comment]
Awesome idea @bgelens - keen to help out!

I could look at putting some integration tests together this weekend if it would help?

**Comment by bgelens** [comment]
Absolutely! Much appreciated

**Comment by kwirkykat** [comment]
@bgelens We've discussed having class-based resources here in the DSC Resource Kit and are completely open to it. It's easier with a *new* module because with existing modules, we would have to suddenly bump the minimum PowerShell version up from 4.0 to 5.0 in order to include the class-based resource.

In order to accommodate proper unit tests though, you will need to split all the functionality of the resource out into a separate module. Then unit test that module as you normally would.

So you'll ultimately end up having 2 modules for one resource:

- MyClassBasedResource.psm1 : Defines the class-based resource with Get/Set/Test essentially as 'wrapper' functions. This file will be tested through integration tests.
- MyClassBasedResourceHelper.psm1 : Contains all the actual functions for the resource. This file will be tested through unit tests. (You can name it something other than 'Helper'. Up to you.)

The resource class will then import that module and just call the Get/Set/Test from there. I know this sounds inconvenient since you essentially have to write Get-TargetResource, Test-TargetResource, Set-TargetResource in the helper module just as you would in a normal script module, but it's the *only* way I've found to get the unit tests to work properly. If you can find a different solution, please let me know! I would love to hear it! At least you don't have to write a mof...

Also, don't forgot to put all your resources (yes, even class-based) in a DscResources folder if you want to join the DSC Resource Kit.

**Comment by bgelens** [comment]
Hi @kwirkykat,

When looking at inbox PSDesiredStateConfiguration Module inbox of Nano Server. The subfolder used for Class based resources is DSCClassResources
![untitled](https://cloud.githubusercontent.com/assets/10071039/19625043/d5433e9c-990d-11e6-9e08-6b76286bb6c5.png)
Shouldn't we follow inbox examples?
I fixed my project to follow your suggestion by creating the DSCResources subfolder and have it imported as nested module for now but wondering if we shouldn't follow the PowerShell team example already out there.

About unit test via secondary module. Only writing class based resources so we are relieved from creating schema.mof feels wrong to me. We want class based resources for all the other reasons to write classes as well. Formal syntax and semantics help us a lot. Moving the actual code away to script module compromises this experience I think.

I created a first batch of unit test for the test method which works fine for me.
```powershell
using module ..\..\DSCResources\DockerService\DockerService.psm1

InModuleScope -ModuleName DockerService {
    Describe 'Test Method' {
        $DockerServiceResource = [DockerService]::new()
        $DockerServiceResource.Path = 'C:\bogus'

        Context 'Type Test' {
            it 'Test should return a bool' {
                $DockerServiceResource.Ensure = [Ensure]::Present
                $DockerServiceResource.Test() | should BeOfType bool
            }
        }

        Context 'Ensure Absent' {
            $DockerServiceResource.Ensure = [Ensure]::Absent

            It "Test should return true when service is absent" {
                Mock -CommandName Get-Service -MockWith { }
                $DockerServiceResource.Test() | should Be $true
            }

            It 'Test should return false when service is present' {
                Mock -CommandName Get-Service -MockWith {[pscustomobject]@{Name='Docker'}}
                $DockerServiceResource.Test() | should Be $false
            }
        }

        Context 'Ensure Present' {
            $DockerServiceResource.Ensure = [Ensure]::Present

            It 'Test should return false when service is missing' {
                Mock -CommandName Get-Service -MockWith { }
                $DockerServiceResource.Test() | should Be $false
            }

            It 'Test should return true when service is present' {
                Mock -CommandName Get-Service -MockWith {[pscustomobject]@{Name='Docker'}}
                $DockerServiceResource.Test() | should Be $true
            }
        }
       
    }
}
```
Couldn't we use this approach?

**Comment by PlagueHO** [comment]
@bgelens - I think where the problem lies with testing class based resources is that the [standard DSC Resource tests](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L191) won't work on class based resources (correct me if I'm wrong here @Kwirkykat).

Example: [these tests](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L191) will fail with class based resources.

I think [this PR](https://github.com/PowerShell/DscResource.Tests/pull/64) was attempting to address this problem but it stalled.

I feel that not running these standard tests for class based resources just adds too much risk.

So, options as I see it:
1. Update the standard tests to work with Class based resources - is this actually possible?
2. Don't use class based resources for DockerDsc.

I'd love to see option 1 happen as more and more class based resources will turn up, but I haven't had the time to look into this myself.

**Comment by cdhunt** [comment]
We can just skip the schema.mof test in the standard tests. Is there any other testing scenario that is a known issue? I would much rather fix/improve the testing options for Class-based resources over breaking them into separate modules.

**Comment by bgelens** [comment]
I just did a PR for the Tests to skip schema validation for Class resources but still include parse error testing.
https://github.com/PowerShell/DscResource.Tests/pull/75

**Comment by kwirkykat** [comment]
@bgelens If your unit tests work then yay! Problem solved!
I ran into a lot of problems with unit testing a class based resource about a month ago (WindowsPackageCab actually) specifically with mocking. The only solution then was the one I described above, but then we decided to just move it to a script resource to provide a version that would work with 4.0...

Anyways, I'm concerned that you have some internal functions ('ResolveDockerDPath', 'DockerDReg') in the class that won't be able to be mocked. Specifically I think you may have problems mocking DockerDReg which will have to be mocked since it could modify the system once you try unit testing the Set operation. You may still need to move that functionality out to a separate module.

I hope it all goes well 👍 You're doing great!

**Comment by cdhunt** [comment]
@kwirkykat, I have some working code for Mocking class members. @bgelens, I can do a PR to help with those tests.

**Comment by bgelens** [comment]
Just merged the Get method unit tests provided by @cdhunt.
@kwirkykat please have a look how Chris did an overwrite of the ResolveDockerDPath method with a temporary scriptmethod https://github.com/bgelens/DockerDsc/pull/1/files
Would this be an acceptable approach?

**Comment by ryanspletzer** [comment]
I've been writing a class-based DSC Resource module over at [ServiceBusForWindowsServerDsc](https://github.com/ryanspletzer/ServiceBusForWindowsServerDsc), and I've been referring back to this issue and the DSC Resource repos frequently.

I've been working to get things in that module lined up to the [High Quality Resource Module Guidelines](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md). Though I can have class-based resources in the DSCResources folder to satisfy the tests with [DSCResource.Tests](https://github.com/PowerShell/DscResource.Tests), when it comes time to actually *run* the class-based resources from the DSCResources, folder you wind up with an error such as:

![image](https://cloud.githubusercontent.com/assets/1481108/23007926/d92880d6-f3d9-11e6-9496-c17a6eda804d.png)

If I simply change the DSCResources folder name to DSCClassResources (using the convention in PSDesiredStateConfiguration module mentioned by @bgelens above), and re-point the NestedModules in the manifest to the DSCClassResources folder, everything works fine:

![image](https://cloud.githubusercontent.com/assets/1481108/23008092/4f3aece0-f3db-11e6-9234-a6fb0f1aab85.png)

It seems as though DSC (using WMF 5.1 here) is choking on trying to load class-based DSC resources from the DSCResources folder because it expects script based resource modules to be there there. Perhaps adding a schema.mof for each class-based resource would ameliorate this? But seems to defeat the purpose of class-based resources...

Now, the only problem with changing to DSCClassResources folder instead of DSCResources folder is DSCResource.Tests doesn't know to look in DSCClassResources... yet. So the unit tests break if you try to use the test template and Initialize-TestEnvironment cmdlet.

I've worked around this for now with what I can only describe as a hack in my [appveyor config](https://github.com/ryanspletzer/ServiceBusForWindowsServerDsc/blob/dev/appveyor.yml#L25-L32) where I copy the DSCClassResources folder to DSCResources, run the tests, and remove it afterwards. (I tried renaming instead but that caused other issues in tests). And also added lines in my unit tests [here](https://github.com/ryanspletzer/ServiceBusForWindowsServerDsc/blob/dev/Tests/Unit/SBAuthorizationRule.Tests.ps1#L11-L16) and [here](https://github.com/ryanspletzer/ServiceBusForWindowsServerDsc/blob/dev/Tests/Unit/SBAuthorizationRule.Tests.ps1#L21). I can probably fix this better with a test harness at some point instead of in each individual test...

Overall I think there should be a preferred, prescriptive approach for testing class-based DSC resources with the standards and test templates, especially if those are to become the preferred approach long term.

**Comment by johlju** [comment]
@ryanspletzer If it is still relevant. There has been improvements to DscResource.Tests to handle DscClassResources folder, if there are still problems, please submit an issue to the DscResource.Tests repo.

**Comment by johlju** [comment]
@bgelens Are you interest of adding the DockerDsc resource module to the DSC Resource Kit?
If so I like to help getting this reviewed according to the new process of getting a resource module added to the DSC Resource Kit.
I have opened an issue to update the text on [How to do a new resource module submission](https://github.com/PowerShell/DscResources/issues/356),
but basically if we gonna submit this resource module to DSC Resource Kit we need to make sure it follows the [Quality Governance](https://github.com/PowerShell/DscResources/blob/master/Naming.md#quality-governance). In this case it is a Class-based resource module, so that would make it interesting as well.

**Comment by bgelens** [comment]
Hi @johlju, I don't have interest in this anymore as I've moved ahead some time ago and [published](https://www.powershellgallery.com/packages/DockerDsc) it myself. I'll close the issue.
