### ISSUE TITLE
Parameter Mandatory Guidelines

### ISSUE THREAD

**Issue by luigilink** [PowerShell/DscResources#209]
What's the right guidelines for Parameter Mandatory in each get/set/test targetresource.
If it's false no need to mention, but it's true, it should be written:

**Good**
`[System.Management.Automation.PSCredential] 
$InstallAccount`

**Bad**
`[parameter(Mandatory = $false)]
[System.Management.Automation.PSCredential] 
$InstallAccount`

**Comment by kwirkykat** [comment]
@luigilink ```[Parameter(Mandatory = $false)]``` should not be used as it is implied for all parameters in PowerShell functions. If you want to point out to the user that the parameter is optional, this should be done in the help comment for the function instead of by declaring this attribute in the code.

An example of how to write the attribute correctly can be seen [here](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-attributes-on-separate-lines), but perhaps, yes, we should also add a best practice not to use ```[Parameter(Mandatory = $false)]```

**Comment by BrianFarnhill** [comment]
I'll throw my two cents in here seeing as the reason @luigilink is bringing this up is my fault.

I thought the logic behind specifying it was essentially the same reason we don't use positional parameters. By not specifying it we rely on people knowing the default behaviour that is implied when it comes out, but by having it there we are very clear what is mandatory and what isn't. So I would argue that putting it in would be a better practice than taking it out and letting it be implied.

**Comment by johlju** [comment]
I would argue for _not_ using `Mandatory = $false`.

First because I think by using `Mandatory = $false` it does not improve the readability which parameter are mandatory or not. 
If a parameter has `Mandatory = $false` on it, the first you see is `Mandatory` and you read it as as 'Oh, it's mandatory' and then you see `$false` and you think '...or not' 😉 

Secondly I don't like adding code that is not necessary. Unless it improves readability.

And third, a parameter that is mandatory could be written as following. _Might not be allowed in style guidelines now._
``` 
[Parameter(Mandatory)]
[System.String]
$Name
```

I my opinion I think for best readability the following would be a good example of writing mandatory and non-mandatory parameters. The eyes likes consistent look and can easily and fast distinguish small differences. Good when reviewing. 😄 

```
function MyFunction
{
    param
    (
        [Parameter(Mandatory)]
        [System.String]
        $Name,
        
        [Parameter()]
        [System.String]
        $ServerName
    )
}
```

As always. I'm happy for whatever we decide, as long as we use the same. 😄 

And finally a big thanks to @luigilink for his efforts in all the repositories he is contributing too which make differences such as this brought to light. 👏 😄

**Comment by PlagueHO** [comment]
@johlju - gets my vote. I also follow the above style when I can. Although I think you're right about ```[Parameter(Mandatory)]``` not being allowed.

**Comment by BrianFarnhill** [comment]
Urgh - fine I'll cave to peer pressure then :P

I'll arrange the updates to be made to SharePointDsc and OfficeOnlineServerDscto bring them up to scratch

**Comment by johlju** [comment]
If we all are in agreement, I think we also need to add a section to the style guideline as well, so this is documented. Like `Parameters using Mandatory attribute`. I could send in a PR with a proposal for that, unless someone else would like to do it.

@kwirkykat is there a reason we use `[Parameter(Mandatory = $true)]` and not `[Parameter(Mandatory)]`?

@BrianFarnhill  Sorry for all the code you need to change. :) But something you can be proud of it that the way we do things in other resources is because of the way you do it in SharePointDsc. You do some great work! 😄

**Comment by kwirkykat** [comment]
@johlju I generally put in ```[Parameter(Mandatory = $true)]``` instead of ```[Parameter(Mandatory)]``` because technically the Mandatory parameter is a boolean and not a switch. You can also have [other values](https://msdn.microsoft.com/en-us/library/ms714348(v=vs.85).aspx) after Mandatory that do not have boolean values (such as Position which takes an int), and I just personally think it looks strange to provide values for some and not others.

You can use either one though. I'm really not a big stickler on this rule to begin with as long as the attribute is in the right place above the parameter declaration.

```[Parameter()]``` feels like the same thing as ```[Parameter(Mandatory = $false)]``` to me. It's just not needed. But I think technically ```[Parameter()]``` probably should be included everywhere just to formally declare the parameters as public cmdlet parameters as the documentation [here](https://msdn.microsoft.com/en-us/library/dd901842(v=vs.85).aspx) describes.

@BrianFarnhill This wouldn't really change anything. You don't need to update SharepointDsc just for style unless you really want to.

**Comment by PlagueHO** [comment]
So to summarize (if I may):
1. Every parameter must include regardless if it actually requires decoration: ```[Parameter()]```
2. A parameter that is mandatory should contain this decoration:  ```[Parameter(Mandatory = $true)]```
3. A parameter that is not mandatory should contain this decoration:  ```[Parameter(Mandatory = $false)]```
4. These guidelines should only be applied to future resources and changes. Updating existing repositories to meet these guidelines is up to the repository administrator(s).

Does the above sound correct?

**Comment by johlju** [comment]
I interpreted @kwirkykat as that number 3 in your summary list should be replaced by number 1. And in future (and current) PRs all parameters should contain number 1 for all non-mandatory parameters. 

But I do think present HQRM resources should adhere to the guidelines in the earliest convenience, to not confuse contributors to what style/method to use. Or at least submit an issue that the resource(s) does not yet follow new guidelines. 
But that just my opinion :)

**Comment by kwirkykat** [comment]
@PlagueHO @johlju
1, 2, and 4 are correct

3 --> A parameter that is not mandatory should **not** contain the decoration ```[Parameter(Mandatory = $false)]``` but instead just use ```[Parameter()]``` as specified in 1

**Comment by PlagueHO** [comment]
@kwirkykat - doh! Thanks for the correction. So:

1. Every parameter must include regardless if it actually requires decoration: ```[Parameter()]```
1. A parameter that is mandatory should contain this decoration: ```[Parameter(Mandatory = $true)]```
1. A parameter that is not mandatory should **not** contain a Mandatory decoration in the ```[Parameter()]```
1. These guidelines should only be applied to future resources and changes. Updating existing repositories to meet these guidelines is up to the repository administrator(s).

**Comment by johlju** [comment]
Added a proposal to the StyleGuildelines.md. let me know if it looks okay and that's what we want. I used @PlagueHO's summation.
