### ISSUE TITLE
Community Call Comments, Questions, and Feedback (October 26)

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/DscResources#210]
This issue is open for the community to submit comments, questions, or feedback from the DSC Resource Kit community call on October 26 1-2PM PDT.

The agenda for the call is available on GitHub [here](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/10-26-16/Agenda.md).

**Comment by PlagueHO** [comment]
Doh! I missed this! :cry:

**Comment by kilasuit** [comment]
Me too due to user error 😭

**Comment by mbreakey3** [comment]
Yeah, there seemed to be some technical issues with Skype.... Please still feel free to post your questions/comments here.

**Comment by johlju** [comment]
Questions:

* How about Gitter? Maintainers doesn't seem to active int he room 'PowerShell\DscResources'. Maybe it wasn't even created by the PSDSC team? Thinking Gitter could be a good place for quick questions, instead of submitting issues.
* (from Gitter) What happened to the 100 char limit in the style guide? Should we not enforce any char limit anymore when reviewing? 
* (from Gitter) How do we know who are the maintainers for a given DSC module? Could we maybe add that to the README.md for each module? And if there are currently no dedicated maintainers for a module, maybe we could add the persons that eventually will come around?

**Comment by mbreakey3** [comment]
@johlju 
1. Yes - That's a good idea, on top of that, we should make it more clear which forms of communication we're using with each program. It's nice for us to be able to have everything in one place - on GitHub, but I can see where it may not be the best way of communicating questions/discussions. Me and Katie are on PowerShell\DscResources, we've just been really behind on responding -_- 
2. As for the char limit, we meant it more as a guideline. Yes, lines over ~100 chars should be broken up as long as it makes the code more readable, but that's very subjective. I'd say it's mostly up to the reviewer's discretion. In tests, especially, we're much more lenient on this 'limit'. For instance, we want descriptive test names, but dividing those lines up looks really messy.
3. I like the idea of naming specific maintainers for DSC modules. Right now there aren't many modules that have a specified maintainer, but we should add the ones that do, and hopefully we'll be growing the maintainers in the future.

**Comment by johlju** [comment]
@mbreakey3 I know what you mean by being behind, I have that problem too :) Just started to wonder if Gitter wasn't an official channel. Good to know that it is! :smile:

1. I think a discussion that will or might result in a change should always be an issue on GitHub.
I think Gitter would be best suitable for questions or help. Depending on the question we might ask the person asking to submit an issue instead.

2. I was loooking for guidance in any of the guidelines when I had a PR with a row that could  have been split up, which was a bit over 100 chars. Mostly to make the Code look bryter in Reviewable and easier to read. Didn't find anything in the guidelines so I did not comment on that. I thought. If there is no guideline, then there is no rule. 
3. Adding more maintainers would be good. Hope you get more backup soon! :smile: 
You probably don't now this yet, but doesn't hurt to ask :)
Will there be community maintainers? Or will it be existing or additional PowerShell team members? 
Are there PowerShell team members (maintainers) outside US?

**Comment by mbreakey3** [comment]
1. I agree. We should add documentation on this as well - probably in our contributing guidelines.
2. Definitely feel free to comment on lines that are over 100 chars if the code would look cleaner if they were split up. We may add a rule in our guidelines for this, but aren't sure. We trust your common sense though 😄 
3. There actually already are some community maintainers, and that's most likely where we will be pulling new maintainers in from.

**Comment by PlagueHO** [comment]
I missed the call because Microsoft went and scheduled Microsoft Ignite NZ for the same time - what were you thinking? :grin:

I had completely forgotten about the Gitter channel PSDSC. TBH, it seemed so dead about 9 months ago that I stopped checking in regularly.

1. I do think issues are better even for simple questions because they get indexed by search engines. So someone else looking for the same answer might show up the issue instead. So the issues list becomes a bit of a knowledge library (I myself have found solutions to issues that way).

2. I do prefer lines to have a limit because it really does help with code reviewing. Besides that, if you don't have an actual rule then people feel like you're being a nit picky if you ask them to refactor a line. It is much easier to get someone to refactor a long line if there is a rule to back it up. I usually try and enforce a 120 char rule because that works well for side-by-side reviews on a 1080p monitor.

3. I try to maintain any modules I've commited to (xNetworking, xDFS, xCertificate, xStorage, xADCSDeployment, SystemLocaleDsc, xTimezone, xDNSServer etc). But like the MSFT DSC Team it can be hard to keep up (combined with a "day job"). There are other maintainers at MSFT I think who are outside the DSC team (e.g. @BrianFarnhill) but I think they also have "day jobs" too (how @BrianFarnhill manages to be so prolific with SharePointDsc and still do another fulltime job is beyond me :smile:). There are lots of contributors though - but not so many stick around as maintainers. It seems we need a way to get contributors to stick around as maintainers.

**Comment by johlju** [comment]
2. Yes, just thinking if I use my common sense and ask a contributor to do it one way, then next reviewer might ask the contributor to do it another way :) 
But from now I will ask for a change when I feel it more suitable another way and if a problem arises we take it from there :)

**Comment by BrianFarnhill** [comment]
@PlagueHO yea I don't know how I fit it in either, I just sit in front of the laptop and out pops SharePoint stuff :P But you're right about the people that contribute vs the people that are dedicated maintainers of a repo. I know I've had people that come and go with pull requests but I'm also lucky enough to have 2 or 3 others that pretty regularly help me chip away at things too. I think really it would be up to the owner of the module to decide who they felt comfortable listing as an active maintainer then maybe?

**Comment by PlagueHO** [comment]
@BrianFarnhill - Haha, lucky for some!

I think being a maintainer doesn't necessarily mean having admin rights to the repo. I think if you're actively reviewing PR's, contributing code, discussing issues and providing support/help on a repo then that could possibly be considered a maintainer (but not administrator). There almost needs to be another "role" defined - a "non-admin maintainer". I consider (not official of course) that my role on repos like xNetworking and xDFS.

**Comment by johlju** [comment]
Regarding @PlagueHO last comment on question 2, I agree totally. It is much easier if there is a rule to back it up, Even if that rule is somewhat leaner, and not strict to one number.

@PlagueHO I agree with the above comment. I also see myself as a contributor that also maintains in the xSQLServer module.
I'm happy to see that more people are starting to contribute code and issues in xSQLServer, and I try to help move that forward. I would like to think that is because contributors now see that things are starting to move forward, and that they contribute more because of that.
To help that even more I see a bigger need for my (limited) time in that module for maintaining (reviews, helping contributors, comment on issues) than doing heavy coding. Since there are others that code in that module, I'm starting to think that after my PR's are merged, I will focus mostly on the maintainer part. And only doing smaller code changes. At least until we have more maintainers. 
It think it would be good if a PR is not idle for more than a week until a maintainer (community/PS Team) is active on it.

**Comment by johlju** [comment]
More questions :smile: 

**Question 4** 
I using interactive rebase when I make typo's or just to clean up the commit history. I thought that might be something I could put together into the GettingStartedWithGithub.md for others to learn and use. Would that be something that would be useful? Thinking of doing just the basics that I use most often like squash, fixup and reword.

**Question 5**
@BrianFarnhill I think I saw somewhere that in a conversation in a PR in SharePointDsc that you wanted the commit history concatenated (or changed in some way) before merge, is that correct? I might have misunderstood the comment in that PR, was a while back, and have not seen you request it since. 

Either way, that got me thinking if we should have a some standard or guideline of the commit message before merge so the commit history don't just contain 'Fixed typo'. Would that be a good idea? Thinking that it could be the last step in the review process, asking the contributor to reword/squash/fixup commit history.

I have started to use several rows in the commit message. On row 1 of the commit message I've started to use 'Changes to <resourcename|md_name>', or if there are additions/removals I try to make a short description in the first row like 'Adding specific contributing guidelines'.
And if I have additional information I feel would be interesting to add to the commit log I put that on seperate rows, like a 'mini change log'.

Examples:

````
Changes to xSQLServerSetup
Added additional tests and cleaned up a little bit more code
Changed some code to be able to mock and improve readability
```

```
Changes to xSQLServerSetup
Removed non-mandatory parameter 'Features' from Get-method
Improved tests with FullText and Reporting Services
Improved tests so the arguments sent to setup.exe is evaluated
```

```
Adding specific contributing guidelines
Adding specific guidelines for contributing to xSQLServer resource (resolves #158)
```

**Comment by johlju** [comment]
The answers for my own question 4 above is that is in my back log, but have very low priority right now, so it someone else want to contribute that feel free. 😄 And in regards to question 5, this is up to the maintainer for each repo what the the commit history should look like. Up to the maintainer to use merge, squash or rebase when merging PR's. I prefer to use squash.

**Comment by johlju** [comment]
I'm closing this issue since it has gone a long time since this community call, and it seems that all questions in this issue is answered. Please comment if that is not true.
