### ISSUE TITLE
Add Markdown Linting to standard tests

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#212]
I use the [MarkdownLint extension for VS Code](https://github.com/DavidAnson/vscode-markdownlint). It highlights problems and rule violations with Markdown files. I've noticed that most Readme.md files in the DSC resource repos contain quite a few violations:
![2016-10-30_11-57-51](https://cloud.githubusercontent.com/assets/7589164/19833272/c1ee526a-9e98-11e6-97bc-b866e63a36d3.png)
The green underlines are violations. They're usually really easy to fix and I fix them as I find them in any resources I'm working on. However it might be worth adding tests that at least highlight these problems in AppVeyor. At this point I wouldn't suggest failing the build, but it might at least be worth addressing at some point.

[Here is a list of linting rules MarkdownLint applies](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md).

I have seen some AppVeyor builds use Atom to automate Markdown Linting, but it should be possible with other methods.

**Comment by BrianFarnhill** [comment]
This is genius, especially since the documentation generator I wrote is based on markdown files for descriptions, so there are so many more bits of markdown kicking around SharePointDsc for example than just a readme file. I'll definitely be installing that extension, but would love to help you get that sort of check going in AppVeyor for the DSC stuff dude.

**Comment by BrianFarnhill** [comment]
@PlagueHO I had a couple of minutes spare and I got most of this done, check out this build

https://ci.appveyor.com/project/BrianFarnhill/sharepointdsc/build/1.4.0.314

I'm using npm to download the bits we need the gulp to run the task - you can see it spit out the output about the rules, I just need to get it to spit out a meaningful error code or something so that it will fail a build on issues. It should also still respect a rules file that is put at the root of the project as well, so that should help a lot as well. I'll let you know when I get it working though.

**Comment by PlagueHO** [comment]
@BrianFarnhill - that is awesome!!! We so need to add that to the standard AppVeyor functions you were putting together so that all repos can call it. That is a fantastic job - leave it to you to solve all the problems :grin:

**Comment by johlju** [comment]
@PlagueHO I installed this when I saw you issuing this. Great tool!
And @BrianFarnhill awesome work getting that in so quickly! Hope you get the last pieces working soon too :)

**Comment by BrianFarnhill** [comment]
Shouldn't be too hard - I think I'm going to get it to output to a text file that I can interrogate in a test or something like that. Have an insanely busy week this week but should have some time next week to get it going for sure.

**Comment by BrianFarnhill** [comment]
OK I think I got it, here's an example of a failed build:

https://ci.appveyor.com/project/BrianFarnhill/sharepointdsc/build/1.4.0.315#L74

and here you can see the same test passing after I cleaned up the files:

https://ci.appveyor.com/project/BrianFarnhill/sharepointdsc/build/1.4.0.316#L70

Now I'm 99% sure this is only looking at MD files in the root directory, so I gotta get that sorted, but the logic of how I'm assessing it and passing it all to pester is done. I'll need to write some doco on this as there are a few new moving parts to consider (but as long as you install nodejs things should just work pretty smoothly as I've set up a package file that will let it download the dependencies) but all in all I think it's a workable solution (and also giving us a JavaScript based task runner to the build pipeline might open up some other options for us later on as well - not sure what yet, but with gulp in place we have plenty of flexibility).

**Comment by PlagueHO** [comment]
@BrianFarnhill - awesome! That is +++ fantastic!

I'm looking at your AppVeyor.psm1 file and wondering if we could centralize and generalize it somehow? Actually I think this is really [this issue](https://github.com/PowerShell/DscResources/issues/205).

So although I'm tempted to just grab all your code and slam it into xNetworking etc, but then we'll just end up with lots of duplicate code across all the repos. So I'm thinking [this PR](https://github.com/PowerShell/DscResources/issues/205) needs to progress.

**Comment by BrianFarnhill** [comment]
OK I've almost got this - it's scanning everything but it's actually giving me some random false positives now - have a look at [this build](https://ci.appveyor.com/project/BrianFarnhill/sharepointdsc/build/1.4.0.318) and then look at the [markdown file it's complaining about](https://github.com/BrianFarnhill/SharePointDsc/commit/2342211a611a472265e9a0a8e40ffe1e4e36f2c1#diff-b5f1c67b950e5f1da2e3cb66b14706ca). It's saying that it should have a top level header, but it already does. I found when I ran this locally I saw similar behaviour as well but it was complaining about a different file. 

@DavidAnson We've grabbed your MarkdownLint project and are trying to use it to scan our markdown files, but it looks like there is a potential false positive here. Since I'm rubbish with JavaScript these days is there any chance you can help us out looking in to whats going on here?

**Comment by DavidAnson** [comment]
@BrianFarnhill Sorry for the trouble! `markdownlint` doesn't have any randomness in the code (or any of the other CI systems it's run under), so your comment that this is random makes me worry it's something to do with your build process. (Is there any chance files get checked when they're being written?) Regarding the file you linked to, it appears fine to my eye. From what I can tell in GitHub, there's no hidden CR/LF at the top to confuse things. You can test yourself at https://dlaa.me/markdownlint/ - there are no errors reported, so I'm not (yet) too suspicious of `markdownlint`. If you can get a reliable way to reproduce the problem, I'd be happy to look into this. If not, I still have good news: I'm about to release an update that includes a bit more information about errors. It's possible that'll help diagnose this issue.

Keep me posted!

**Comment by BrianFarnhill** [comment]
@DavidAnson Is there any chance you can take a clone of [my branch](https://github.com/BrianFarnhill/SharePointDsc/tree/feature-markdownlint) and see if it shows you the failure on your end as well? If you just fork that out and then run the gulp task "test-mdsyntax" it'll drop any of the errors it finds in to a text file there called markdownissues.txt (the gulp file is pretty straightforward, based on your example for integrating with gulp). You could even swap the gulpfile out for your exact example to just output to the screen if that helps. Would definitely appreciate it if you could validate if this is a "me" problem or not! :)

**Comment by DavidAnson** [comment]
@BrianFarnhill Gulp runs things in parallel as much as it can. Here's the output I got:

```
D:\T\SharePointDsc\Modules\SharePointDsc\DSCResources\MSFT_SPWebAppWorkflowSettings\readme.md: 1: MD041 First line in file should be a top level headerer
```

Note specifically the last few characters - the message is not "headerer". Every file you lint writes to the same output file, `markdownissues.txt`, so they're probably all overwriting each other as they run.

I apologize because I led you into this with my sample which operates the same way - though to the console where I think things may be serialized automatically.

There should be a fairly trivial way to gather all the files and then lint them all in a single action. I hope to update my sample shortly and that should address the issue you're seeing.

**Comment by BrianFarnhill** [comment]
@DavidAnson Ahhhh that makes way more sense actually! It makes a few other weird things I've been seeing make so much more sense as well actually. Will wait to see your updated sample, thanks heaps!

**Comment by DavidAnson** [comment]
Okay, two things, actually. :)

First, here's a version of your `gulpfile.js` that serializes output like you want:

```js
var gulp = require("gulp");
var concat = require("gulp-concat");
var through2 = require("through2");
var markdownlint = require("markdownlint");
var fs = require('fs');

gulp.task("test-mdsyntax", function task() {
  return gulp.src("Modules/**/*.md", { "read": false })
    .pipe(through2.obj(function obj(file, enc, next) {
      markdownlint(
        { "files": [ file.path ] },
        function callback(err, result) {
          var resultString = (result || "").toString();
          if (resultString) {
            file.contents = new Buffer(resultString);
          }
          next(err, file);
        });
    }))
    .pipe(concat("markdownissues.txt"))
    .pipe(gulp.dest("."));
});
```

Good, one problem solved! (I'm not sure I want to update my Gulp sample because this seems like a slightly unusual pattern, but I'll think about it more before deciding.)

However, you'll note that many files still report MD041. Now that I have the files locally, I can see they all have a UTF-8 BOM at the front which apparently is not ignored by `markdownlint`. I'll fix that for the upcoming release (ETA now tomorrow or the next day).

In the meanwhile, you might disable MD041 if you don't want to deal with the noise.

Thanks for bringing this up!

**Comment by BrianFarnhill** [comment]
@DavidAnson You are my hero! So I'm super close to what we need here now (I'll deal with the file encoding issues myself, they shouldn't have the BOM bit, they should be straight up UTF8), my current issue is trying to get the results to come out one per line in my text file. I changed the buffer to add a new line:

    file.contents = new Buffer(resultString + '\r\n');

and that works where there is only one issue per file, but files with more than one issue seem to come out as a giant blob when I look at it in notepad. Any ideas on that one? I can probably handle this with some string manipulation in my PowerShell script if I have to but I figure there's no harm in asking.

**Comment by DavidAnson** [comment]
`gulp-concat` is supposed to respect the host OS's newline preferences, but doesn't seem to be doing so. Try this:

```js
.pipe(concat("markdownissues.txt", { newLine: "\r\n" }))
```

**Comment by BrianFarnhill** [comment]
@DavidAnson Notepad still looks like rubbish when I do that but PowerShell and opening it in wordpad seems to behave right now, so that will work for me! That's everything I need to get this one going for us, thanks so much for your help

@PlagueHO Wanna have a chat about how we make this test something generic? I'm thinking I'll still roll it in to SharePointDsc as it is rather than wait for that but would love to help work it in somehow if we can

**Comment by PlagueHO** [comment]
@BrianFarnhill - that is awesome going! Total legend mate!

What I was thinking was that we need a new PS Module (in a new repo probably) that should contain generalized versions of all the awesome processes you've created for SharePointDsc. If we can get a decision about how to centralize all these deployment type code then I could start making progress.

So I reckon if we can get the DSC team to weigh in on: https://github.com/PowerShell/DscResources/issues/205 then we can start building the stuff out.

**Comment by BrianFarnhill** [comment]
I've opened a PR with my changes for SharePointDsc - the last bits I added was support for a rules file that both VSCode and AppVeyor will honour. It's all working great now, so next step is to get this all merged in. @PlagueHO Let me know if you need a hand making this change (if you still wanna be the one to push that in)

**Comment by kwirkykat** [comment]
Cool 🐱 I'm on board

**Comment by PlagueHO** [comment]
This is completed so I'll close it.
