### ISSUE TITLE
xSCEP module available but needs community assistance

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/DscResources#213]
A module for System Center Endpoint Protection has been developed but needs tests and documentation to be considered for the resource kit.
[https://github.com/robwi/xSCEP](https://github.com/robwi/xSCEP)

HELP WANTED

**Comment by johlju** [comment]
This is labeled as help wanted so that anyone in the community can run with it. Please note that the DSC Resource Kit no longer accepts new resource modules. Any contributor may make a module submission of there own resource module, so basically the resource module is linked as a submodule in this repository (linking it to the DSC Resource Kit). 

*As the DSC Resource Kit no longer accepts new resource modules, this issue might be closed in the future.*

**Comment by johlju** [comment]
This issue was moved here: https://github.com/PowerShell/xSystemSecurity/issues/24
