### ISSUE TITLE
Remove "No Backslash in Paths" Style Guideline

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#249]
[This rule](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#no-backslash-in-paths) is not required as PowerShell will translate backslashes to the format of the OS.

The rule should be removed as it results in code that can be difficult to read and maintain and is not necessary.

I am raising this as @TravisEz13 and I discussed this in [this PR](https://github.com/PowerShell/DscResource.Tests/pull/110).

**Comment by briantist** [comment]
I disagree with this. While (some) PowerShell cmdlets may interpret backslashes as `PathSeparator` on different platforms, there are many possibilities for this to go wrong. Even when that's not the case, I avoid backslahes in my own code (even when I know it will only ever run on Windows) and prefer to use `Split-Path` / `Join-Path` or `[System.IO.Path]::Combine()`. 

I think in most cases where this makes code difficult to read, it's a code smell that indicates path concatenation should be moved to a different function / method, or otherwise abstracted.

**Comment by BrianFarnhill** [comment]
I agree with @PlagueHO that using the join and split paths instead of the backslashes leads to code that is harder to understand. 

That said, I understand the point @briantist is making in that not all cmdlets will do the interpretation. But I think that given the majority of our resources target applications and elements that are specific to a single platform (namely Windows) it's a bit of a pointless discussion. I understand that taking the backslashes out makes the script more portable between platforms, but given most of our resources will never need to do that the rule isn't something that should apply to every resource.

So perhaps the change to the style guideline is to say "No backslash in file paths for modules that are not dependent on a specific platform" so that way when we are writing code that only ever exists on Windows we can avoid the messier code, but on stuff that will run on other platforms we enforce the rule to ensure it will work consistently on both platforms.

**Comment by TravisEz13** [comment]
`(Resolve-Path $somePowerShellPath).providerpath` will give you the correct native format on each platform.

**Comment by PlagueHO** [comment]
Perhaps the rule could be something like:

To support the possibility of cross-platform use in the future, paths must be converted to use the operating system native path separator before being used:
**Bad:**
```powershell
$currentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module -Name "$currentPath\..\..\CommonResourceHelper.psm1"
```

**Good:**
```powershell
$currentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
Import-Module -Name (Resolve-Path -Path "$currentPath\..\..\CommonResourceHelper.psm1").ProviderPath
```

**Comment by johlju** [comment]
But it doesn't work for paths that do not exist. If I want to create folder Temp2 under C: 
```powershell
PS > New-Item -Path (resolve-path -Path 'C:\Temp2').ProviderPath -ItemType Directory
```
Will return
```
resolve-path : Cannot find path 'C:\Temp2' because it does not exist.
At line:1 char:17
+ New-Item -Path (resolve-path -Path 'C:\Temp2').ProviderPath -ItemType ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp2:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand

New-Item : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:16
+ New-Item -Path (resolve-path -Path 'C:\Temp2').ProviderPath -ItemType ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by PlagueHO** [comment]
@johlju - an excellent point! Back to the drawing board!

We could recommend something like:
```powershell
("$currentPath\..\..\CommonResourceHelper.psm1".Replace([System.IO.Path]::AltDirectorySeparatorChar,[System.IO.Path]::DirectorySeparatorChar))
```
But that is really long winded and not really elegant. There must be a better way?

**Comment by johlju** [comment]
Yes I agree with that 😄 That is worse than using `Join-Path` and `Split-Path`. Couldn't we just invent our own `Resolve-Path` cmdlet that works with paths that does not exist? In that we could use your last suggestion.
That can be in CommonResourceHelper.psm1 or where ever.

**Comment by johlju** [comment]
Could't we just say, that if it a relative path, or a path is concatenated together with a cmdlet that generates a OS independent path, then one must just any method that is appropriate to not hard-code back-slashes or forward-slashes.

If there is an absolute path like 'C:\' then there should not be a need to remove backslashes, because that path will only work on Windows anyway. There is not a guideline that say we must always use relative paths?

**Comment by johlju** [comment]
I suggest we just add the following to the [rule text](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#no-backslash-in-paths)

"If the code targets applications or elements that are specific to a single platform it is not necessary to use `Join-Path` and `Split-Path`  to build the path."

Then it's up to the maintainer to enforce it or not.

**Comment by TravisEz13** [comment]
FYI, in PowerShell 6, the path must exist on windows if you use a rooted path (a path starting with a driver letter or share) even for `Join-Path`
https://github.com/PowerShell/PowerShell/issues/4386

**Comment by johlju** [comment]
Thanks for that information! I had to test this, and in my test this is also true for Windows PowerShell 5.1.14409.1005 and above, see my comment https://github.com/PowerShell/PowerShell/issues/4386#issuecomment-382309339. 

But that is yet an argument that is should be up to the maintainer to determine if `Join-Path`/`Split-Path` should be used.
