### ISSUE TITLE
Comment-based help for Get-, Set-, Test-method in mof resources

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#253]
I need some guidance for a discussion that @randomnote1 and I had over at https://github.com/PowerShell/xSQLServer/issues/425.

Currently (in xSQLServer at least) we document parameter descriptions in three places; schema.mof file, comment-based help, and the README.md. The same parameter description in all three places.
If we use the document helper, we don't have to document in the README.md. Because those will be built automatically from the schema.mof.
But when we add that functionality we still have to document the same description in the comment-based help in the .psm1 file as well as in the schema.mof file. We do that because there is a style guideline saying we should. But that seems redundant. 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#functions-have-comment-based-help

Do we need the comment-based help for the Get-, Set- and Test-methods, if so, why do we need them? :)

**Comment by zjalexander** [comment]
related: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088453-inline-help-for-dsc-resource-properties

**Comment by tysonjhayes** [comment]
IMO - we shouldn't need comment based help. With the ability to auto-gen the documentation using our existing modules the schema should be our source of truth. To me the comment based help doesn't get us much.

**Comment by PlagueHO** [comment]
I'd +1 that!

**Comment by BrianFarnhill** [comment]
I agree with @tysonjhayes and @PlagueHO - the documentation generation gives us a wiki for github as well as the PowerShell based helped through "Get-Help about_[resourcename]" so I don't think we need comment based help at all.

**Comment by johlju** [comment]
@zjalexander Apparently there is no comment-based help in class based resources yet. https://github.com/PowerShell/PowerShell/issues/2225

**Comment by johlju** [comment]
@kwirkykat and @mbreakey3 what do you say? :) You two are the deciding vote :wink:

**Comment by kwirkykat** [comment]
Awwwww. I love the comment-based help 😿

I do agree it's annoying to have to copy descriptions everywhere, but I am wary to just remove the comment-based help since there are some valuable dev notes that we put in the help comments that don't go into the README. Like knowing if a parameter is included in say Test-TargetResource but isn't used in that function.

Plus the parameters often act differently between the Get/Set/Test functions and I use the help comments to document some of those differences. Like the Validate parameter in xArchive/Archive as an example: https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xArchive/MSFT_xArchive.psm1#L201

Also with the help comments in the code you don't need to have internet connection or have to find the module's README in order to understand how to use the resource or edit the code. It's all right there above the function.

Maybe I'm just too attached to my pretty help comments...

@mbreakey3 What do you think?

**Comment by mbreakey3** [comment]
I agree with @kwirkykat on this one. While it is somewhat of a pain to have them copied in multiple places, I do find the help comments more helpful than not.

**Comment by johlju** [comment]
@kwirkykat @mbreakey3 It might be us that is not using the comment-based help as much as you guys do. Maybe the problem is that we should use it more. Right now 99% of the times it is just the same description as in the README.md (in xSQLServer at least).

But more thoughts...

In the DSC resources how a parameter should be used is put into the README.md (and copied to schema and comment-based help). If we instead added the description to the README.md (if not using "Auto-Documentation") and to the schema.mof. Then let the comment-based help just contain information about things that a coder would appreciate.
That would mean that adding all parameters to the comment-based help would be optional. But a requirement to add the parameter to the comment-based help if another guideline says you need to document something, like if a parameter is not used in a method. But at least we don't need to copy the same parameter description to the comment-based help.

When I code, for xSQLServer, or a user of a resource, if I need to know how a parameter is expected to work then I look at the README.md. I do not look at the comment-based help. The README is the original, because that is what the user reads.

Comment-based help should be mandatory for all helper functions though.

@mbreakey3 @kwirkykat you guys have veto 😄 We follow. 😉

**Comment by johlju** [comment]
Closing since I think we came to the consensus to keep the comment-based help, also as per style guidelines.
