### ISSUE TITLE
PowerShell DSC 5.1 report filter API doesn't work

### ISSUE THREAD

**Issue by chancein007** [PowerShell/DscResources#255]
I setup the WMF 5.1 and DSC report server 5.1, I tried to do the filter to return the specified number of DSC report entry data using the below similar request URL, howerver, it doesn't work. 
Step1 $count filter worked well by invoking the below URL http://pullserver.example.com:8080/PSDSCPullServer.svc/Nodes(AgentId='2EF12B0F-E2C2-11E6-9A0F-9A320D9CC830')/Reports/$count and it return 1141.

Step2. I used the below URL by adding filter $top=2, howerver, the DSC report server still returned all of 1141 records rather than 2 records. http://pullserver.example.com:8080/PSDSCPullServer.svc/Nodes(AgentId='2EF12B0F-E2C2-11E6-9A0F-9A320D9CC830')/Reports?$top=2

Is there guy who can help me? Thanks in advanced.

**Comment by grayzu** [comment]
$top has not been implemented on the server side, unfortunately. You can, however, filter the results in PS once the results are returned. 

Have you looked at using Azure Automation DSC? It provides very robust reporting functionality.

Since this is not an issue with DscResources, please post questions like this on UserVoice: https://windowsserver.uservoice.com/forums/301869-powershell/category/148047-desired-state-configuration-dsc

MarkG

**Comment by chancein007** [comment]
Much appreciated for your quick reply. We can't access to internet due to our limited network environment.
