### ISSUE TITLE
Style Guideline: Parameter Types / Types in general

### ISSUE THREAD

**Issue by raandree** [PowerShell/DscResources#259]
Some people use the long names (System.String or System.Boolean) when defining type names for parameters or inside a function, some use the short names (string or bool). Sometimes the short names are all lowercase and sometimes Pascal case.

I would like to suggest to use the short name for well-known standard types as defined in PowerShell. You can get a list of these short names or accelerators like this:

``` PowerShell
[psobject].Assembly.GetType("System.Management.Automation.TypeAccelerators")::Get 
```

For all other types I would like to suggest to use the full name, Pascal case.

**Comment by johlju** [comment]
Style guideline does not use [System.*] for the type declaration. But there is not guideline saying etiher. 
Example: https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-type-on-line-above
So I guess that some use, or do not use, [System.*] is just by habit.  I open to go either way. But as always I like consistency. Myself have ignored if a contributor is mixing type declarations in the same file, since there is no guideline to enforce. And I know that I myself are mixing (especially when doing copy/paste), but I try to use [System.*]

**Comment by briantist** [comment]
I use `[System.*]` because that's what tab-completion does.

**Comment by raandree** [comment]
using tab-completion to complete ```[stri``` results in ```[string```, as there is a shortcut to System.String. If you start typing ```[System.Str``` then it gets completed to ```[System.Sting```.

So it depends on what you provide to tab-completion.

**Comment by briantist** [comment]
@raandree  yes true. I was speaking specifically about cases where there is no type accelerator, as in `[System.Collections.ArrayList]` vs `[Collections.ArrayList]`.

**Comment by PlagueHO** [comment]
I can definitely see good reasons for doing it both ways. For me though the priority is usually consistency and managing tech debt. If this becomes a standard then we should see if we can add helpers to dscresource.test to test for and also fix any violations. This might be quite easy using the PS AST. We've done this for other requirements and standards before.

Just my 2c :grin:

**Comment by johlju** [comment]
I agrre what @PlagueHO is saying. If we are gonna enforce a style we can make a common test for it.
But @PlagueHO what do you mean by "fix violations"? Change the contributors code in the test? That sounds wrong. 😄 

Would it be "faster" to run code using [System.String] than code using [String], or vice verse? If we should enforce one style over another there should be some benefit to why we do it on way and not the other. Or will the only benefit (which will be good enough) that all use the same style?
If the later I open for not using accelerators, but using `[Microsoft.Management.Infrastructure.CimInstance]` and `[System.String]`, the same way we enforce using named parameters.

**Comment by PlagueHO** [comment]
@johlju - oh no, not automatic fixing - more like adding a function to [MetaFixers.psm1](https://github.com/PowerShell/DscResource.Tests/blob/dev/MetaFixers.psm1) that users could run to fix any violations in their repo.

I'd also prefer to not use the accelerators if there is no difference in performance.

**Comment by johlju** [comment]
@PlagueHO Ah, did not know about them. Missed those. 😄

**Comment by PlagueHO** [comment]
@johlju - I've only ever had to use it twice that I can recall - but if there were some more useful fixers in there e.g. convert all type accelerators to full type or a more generic fixupparameterblocks then this could save much time in fixing PRs and code review comments :grin:

**Comment by PlagueHO** [comment]
@mbreakey3 - do you have any thoughts on this from the DSC Team perspective?

**Comment by bgelens** [comment]
Just my 2ct. 

When people use [xDscResourceDesigner](https://github.com/PowerShell/xDSCResourceDesigner), they will end up with the full name ```[System.String]```, ```[System.Boolean]```, etc.

Personally I don't really care. Both ways are fine with me.

**Comment by PlagueHO** [comment]
@bgelens - I've found myself preferring the full type name now and have been standardizing on it anyway. I think @johlju has also done the same. And if xDscResourceDesigner produces full name types then I'd say we should make that the standard.

What I feel matters most is consistency - it makes reviews much easier if we know that all repos should meet a certain style - otherwise we have to remember what the style is for each repo (which gets difficult when you're doing reviews for repos you don't often do them for).

**Comment by mbreakey3** [comment]
I also don't really have a preference on this. Mostly we've been allowing both styles in reviews. Personally, I don't like having too many nitty-gritty style rules because it can discourage newcomers from contributing to the resource kit at all, but I understand from a reviewer's standpoint, it is easier to be able to refer to the guidelines when making review comments. If you want to have this standard particularly for HQRMs, then I would be more on board with that, but I'm hesitant to add it in as a hard rule in the guidelines.

**Comment by raandree** [comment]
Great, I am also happy with a bit more freedom here. This topic came up duing a code review and is answered now. Thanks all!
