### ISSUE TITLE
Certificate thumbprints in various resources

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/DscResources#261]
Many resources require a certificate thumbprint as part of their properties however there are times when this isn't possible to provide as you're using xCertReq or similar to generate the certificate at the same time. It would be useful to be able to specify the Subject of the certificate and have the resource grab the thumbprint based on that at run time, assuming DependsOn is set to wait for the xCertReq or similar to generate the certificate first.

I've already done one simple way of handling this in the ryanspletzer/ServiceBusForWindowsServerDsc#36 repo but this doesn't take into account handling expired certificates or multiple certificates with the same subject which will be something that needs to be dealt with, I'm working on that for this resource already.

Is this a viable addition to resources? I'm more than happy to contribute and help out with this but I figure a discussion of how this could or should be handled within the code is useful, especially given how simplistic my initial approach is and how many cases it doesn't cover (multiple certs is the main problem).

Edit: There is a pretty good example that I've found by @PlagueHO in the WSManDsc resources [found here](https://github.com/PlagueHO/WSManDsc/blob/dev/DSCResources/MSFT_WSManListener/MSFT_WSManListener.psm1#L155) that I think could be quite a good baseline for developing further, obviously with changes needed depending on the usage of the certificate.

**Comment by BrianFarnhill** [comment]
I actually like this idea a lot, I know there are a few of these in SharePointDsc and OfficeOnlineServerDsc that I look after that I think could benefit from this approach. We typically use a thumbprint because that's what the SharePoint cmdlets we call use, so we just pass the parameter through - but it wouldn't be difficult for us to say something like "if its a thumbprint pass it through, otherwise look it up from the cert store" kind of thing to enable this functionality without us making a breading change to current behaviour.

**Comment by ChrisLGardner** [comment]
That's probably the easiest approach, similar to how I've done it for the ServiceBusDsc. If you get a subject then look up the thumbprint and use that instead, do it early enough in the resource and you only need to add a few lines to handle it and the rest works as currently.

I'm curious how we work out which certificate is most appropriate to use though, especially in cases where there might be more than one certificate with the same subject. We pick the one with the correct key usage and extended key usage for our use case (mostly SSL certs and similar from what I've seen), but then do we default to the longest expiry date?


What's the behaviour for ApplyAndAutoCorrect in this situation? If a cert expires do we hope that xCertReq (or whatever gets the cert) renews it and keeps the same thumbprint? I haven't looked into xCertReq enough to know if it does auto renew for ApplyAndAutoCorrect situations where a cert would expire.

**Comment by PlagueHO** [comment]
xCertReq will attempt to Auto Renew expired certificates if the AutoRenew parameter is set. But as for the situation you're talking about, I proposed a similar solution [over here in xWebAdministration](https://github.com/PowerShell/xWebAdministration/issues/235) to manage SSL certificate renewals and bindings, but I haven't had time to implement it.

However, I think there needs to be a better solution to this kind of problem engineered into the core of DSC.

I think there needs to be a few features added to DSC:
1. A DSC **Property Bag** to be implemented (like Chef has). This would be part of the LCM and would allow machine specific objects/variables to be set, retrieved and optionally persisted. A use case for this would be to allow an Administrator to set information about a node to be used during the consistency checks- this would dramatically reduce the number of "one-off" node configurations need.

For example: I have many nodes that all have SSL bindings created for them. They each have different SAN values that need to be specified in the certificates. I currently need to maintain a different node configuration for each node, because the SAN name can't be defined at Runtime by the node - it has to be defined at compile time. Having a **Property Bag** would allow me to define the SAN for each node and then the actual node config would consume that value.

2. The ability for a DSC Resource to store information (in either Test-TargetResource or Set-TargetResource) in the **Property Bag** and make it available during a consistency check to all resources. E.g. xCertReq could record the thumbprint of the certificate that was either requested (or matched) for use by another resource further on in the consistency check.

3. The ability for the parameters assigned to resources to be pulled from the **Property Bag** at run-time somehow. E.g. you could do something like with the xCertReq.
```powershell
        xCertReq SSLCert
        {
            CARootName                = 'test-dc01-ca'
            CAServerFQDN              = 'dc01.test.pha'
            Subject                   = '{[PropertyBag] CertificateSubject}'
            KeyLength                 = '1024'
            Exportable                = $true
            ProviderName              = '"Microsoft RSA SChannel Cryptographic Provider"'
            OID                       = '1.3.6.1.5.5.7.3.1'
            KeyUsage                  = '0xa0'
            CertificateTemplate       = 'WebServer'
            AutoRenew                 = $true
            Credential                = $Credential
}
```

Anyway, sorry about the long winded discussion abut this, but I've run into this sort of challenge a lot and end up writing complicated xScript resources to address it and end up with far too many "one-off" MOF Files.

My 2c

**Comment by bgelens** [comment]
Just adding my 2cents. We have been discussing this need for data exchange and notification / action ability between resources for a long time with the PS team already (since the beginning of DSC actually).
On Uservoice :
* https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13399734-returning-information-from-dsc-resource-to-another
* https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13559037-feature-req-exchange-data-between-resources?tracking_code=b52ff26ff6e91bf58210b66f06ff794b

**Comment by johlju** [comment]
I asked if this could be considered for a future LCM - it might or might not be considered. I suggest you [add your proposal as a uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/?query=LCM), if it doesn't already exist, so that you can track it and other users can vote on it.

I'm closing this issue at this time since we can't do anything more about it in this repository.
