### ISSUE TITLE
Drop c/x nomenclature

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/DscResources#27]
A couple of days ago @smurawski made a [blog post](http://stevenmurawski.com/powershell/2015/6/dsc-people-lets-stop-using-c-now) about dropping the c nomenclature from the resources. I think this is a great idea and think we should drop x as well. All my arguements boil down to, "why do we really need it?" It's on GitHub now, everyone can contriubte, and IMO we should be trying to push more stuff into these repros/projects and an forks that occur can be easily traceable through GitHub.

Thoughts?

**Comment by smurawski** [comment]
:+1:  My one caveat is that MS may want to reserve the right to pull the resources in-box and drop the x to differentiate them.  However, now that there is a precedent for shipping open source in Windows (Pester and PowerShellPackageManagement), this might not be the case - so "off with the 'x'"!

**Comment by Iristyle** [comment]
FWIW, at Puppet we've had the same types of discussions around these prefixes and moving the resources in-box eventually.  I'm personally in favor of no prefixes as well.

**Comment by ferventcoder** [comment]
Anything in xPSDesiredStateConfiguration might have issues dropping the x. :)

**Comment by nanalakshmanan** [comment]
Things are a lot different now than when we started the resource kit. So yes these should eventually be gone. As a start, once we are done integrating all community contributions, we should deprecate all the "c" versions. As a second step we should look into deprecating "x". We want to ensure that resources pertain to all best practices - like having tests, etc - before we drop the "x".

**Comment by smurawski** [comment]
@nanalakshmanan @dlwyatt @vors  - I've started removing "c" resources (from PowerShellOrg) that did not have any changes since forking from the origin "x" resource.  I'm also trying to get as may "c" resources shipped to the gallery, so we can focus on getting changes merged back to the "x" projects.

**Comment by vors** [comment]
:+1:

About merging changes from 'c' to 'x': 
It takes a lot of time to review such changes and sometimes they rise questions, we don't want merge particular pieces, yada yada. 
Also, there are some style-guide changes that needs to happen on almost every such PR to make our common tests happy. And sometimes PR's authors just ignore CI build red status. 
We, on the our end, usually don't review PRs that are not **green** and **cla-signed**. So we can end-up in situation, when everybody want changes to be merged, but there is a miscommunication in expectations about who should do the next move. All this complications make it very easy to loose track on meaningful, complex PRs.

Here is how we can approach it: lets **reference this issue** in PR that merge 'c' changes to 'x' versions. Then, because GitHub does the awesome job about "cross issue / pr" mentioning we would have a central place (this issue) to keep track of what need to be merged and prioritize this PR reviews.

**Comment by KarolKaczmarek** [comment]
Sounds like a simple yet efficient plan to coordinate this effort @vors

**Comment by tysonjhayes** [comment]
I like the plan so far @vors. :+1:

**Comment by KarolKaczmarek** [comment]
The RFC on this has been posted here: https://github.com/PowerShell/PowerShell-RFC/issues/10

**Comment by johlju** [comment]
There are now an updated [Naming.md](https://github.com/PowerShell/DscResources/blob/master/Naming.md#deprecated-experimental) that deprecates both 'c' and 'x'. 

> The "x" prefix is no longer required. Resources that include the prefix are free to deprecate the convention going forward.

> Similar to the "x" prefix, at the launch of DSC there was communication that people contributing their own DSC resources prefix it with "c". This was because the resource modules were distributed via TechNet. Since we have moved to GitHub, this requirement is no longer valid.

Resource modules can be named using 'Dsc' as a suffix, or not, see [Module Naming](https://github.com/PowerShell/DscResources/blob/master/Naming.md#module-naming) for suggestions on how to name and tag modules. 

If there are no outstanding questions in this issue, I suggest we close this issue.

**Comment by PlagueHO** [comment]
Wow - this one is old! It gets my vote too :grin:

**Comment by johlju** [comment]
Closing this as solved as per the two previous comments.
