### ISSUE TITLE
Add Guideline for Exported Cmdlet Naming Conventions

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResources#274]
To ensure that DSC Resource kit modules exported functions don't conflict with each other, we should add a naming policy around exported functions. See: https://github.com/PowerShell/DscResources/issues/273#issuecomment-305637218

**Comment by johlju** [comment]
The guideline, should it say something like this?

"Since we don't use the `RootModule` key in the module manifest, we should not use `NestedModules` key to add modules that export functions that are shared between resource modules. 

Normally a single module listed in `RootModule` key can restrict what is exported using `Export-ModuleMember`. Since we don't use the `RootModule` key we can't restrict what is exported, so every nested module will export all the commands (or all the commands restricted by `Export-ModuleMember` in that individual nested module). If two resource modules would use this method that would result in one of them unable to install since they have conflicting exported commands. "

**Comment by johlju** [comment]
@PlagueHO I added PR #393.
