### ISSUE TITLE
Validating Verbose Output in Unit Testing

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/DscResources#290]
Verbose messages are how we convey information to the end user. Often time the verbose messages combined with the error messages allow the end user to more easily troubleshoot their configurations.
Additionally, with the focus on localization, it might be smart to test the localization paths.

The question for the team is, should we start testing verbose output? If so, how should testing be conducted?

**Comment by johlju** [comment]
I agree that testing if the verbose output is actually correct would help test so that changes does not  remove much need information for the user.

But how would we go about mocking this. If using `Write-Verbose` we could mock that, but we could only mock it by passing a parameter filter with the actual message we are expecting, and the assert that mock.

```
InModuleScope {
    $mockWriteVerbose_UsingPath = {
        $Message -eq ($script:localizedData.UsingPath `
                        -f (Join-Path -Path $testParameters.SourcePath -ChildPath 'setup.exe'))
    }

    Describe 'Get-TargetResource' {
        Context 'When the system is not in desired state' {
            BeforeEach {
                $testParameters += @{
                    InstanceName = $mockDefaultInstance_InstanceName
                    SourceCredential = $null
                    SourcePath = $mockSourcePath
                }

                Mock -CommandName Write-Verbose -ParameterFilter $mockWriteVerbose_UsingPath
            }

            It 'Should return the same values as passed as parameters' {
                $result = Get-TargetResource @testParameters
                $result.InstanceName | Should Be $testParameters.InstanceName

                Assert-MockCalled -CommandName Write-Verbose -Exactly -Times 1 `
                    -ParameterFilter $mockWriteVerbose_UsingPath -Scope It
            }            
        }
    }
}
```

But it would be simpler to have a helper function that is writing verbose messages, which then could be mocked, which could be mocked the same way as above, but then the parameter filter only need to be, for example `LocalizationStringKey` which just evaluates the key `UsingPath`. But that would not test the actual verbose message.

Also I think we need to add issue #236 before we starting to get localization in different languages. This would be able to test so that strings has a standardized serial number of some sort (but maybe that test could be a common test).

This should also apply to `Write-Warning` and `Write-Debug`.

**Comment by BrianFarnhill** [comment]
I would actually question the value we would get from testing the output to the user here. Surely if you can test that certain cmdlets get fired off (using Assert-Mock) that should tell you that the code paths are being followed as expected - what value does testing a verbose call add on top of that? Just playing devils advocate here :)

**Comment by scottleyg** [comment]
There may also be boundary cases where ConvertTo-Json is called on a null
as part of a message:

Write-Verbose "your obj is $(ConvertTo-Json $obj)"

This would actually break your execution.  This leads to more justificaton
to log objects and messages through a helper.  Testing loggers is not
useful, but testing that the implementation does not break functionality is
important.   I think that static analysis of Write-Verbose or other log
facilities would be more helpful than unit tests.

Regards,
Scottley

**Comment by kwirkykat** [comment]
@randomnote1 Cool idea.
@scottleyg Makes a good point. Sometimes we do find bugs because we forgot to run with -Verbose. Most frequent one is that we forgot to add a localized string that we are trying to reference.

We could just add -Verbose to all the tests. It would actually be good to have the verbose output on in the automated tests for debugging purposes, but **so. much. text.** Maybe we could redirect the verbose output to a file that AppVeyor posts as a result rather than in the console.

**Comment by PlagueHO** [comment]
I've been trying to convert all tests to call *-TargetResource etc with `-Verbose` because I do find it helpful - even if it is a lot of text :grin:

**Comment by BrianFarnhill** [comment]
@PlagueHO @kwirkykat Yea there is no way we could turn that on for SharePointDsc - we already have enough text to cause issues with loading and scrolling on the page in AppVeyor, so lets try the redirection thing first ;)

**Comment by PlagueHO** [comment]
@BrianFarnhill - that is fair enough! I only switch it on in the case of modules where there is only a few resources.

**Comment by johlju** [comment]
I see these options for unit tests (integration test template is already suggesting to use -Verbose)

1. Add `-Verbose` to unit test template. Then it's up to maintainer to enforce or not.
2. Option 1 plus update template to also suggest adding tests like we do for error messages to test that the correct error messages is thrown. We could add tests to assert that `Write-Verbose` is called with the correct localized messages. Then it's up to maintainer to enforce or not.

To actually test verbose messages I'm in favor of 2.
