### ISSUE TITLE
Possibility to compile dsc document in both ARM and PowerShell

### ISSUE THREAD

**Issue by shurick81** [PowerShell/DscResources#308]
Is there a proper approach for compiling the same document in both Azure and PowerShell?

When I create a DSC configuration document, the only way compile it by running one command that I know of is adding a line for calling the configuration function itself, like this:

```
Configuration SP2013EntDevEnv
{
...
}
SP2013EntDevEnv -ConfigurationData $configurationData
```

At the contrast, if I want to feed my ps1 to the ARM, I have to remove this last line so that Azure does not reject it.

So as I can see it now, there is no proper way of developing only one document that I can use from time to time in PowerShell or Azure. Unless I don't know how to do it right.

**Comment by scottleyg** [comment]
The last line in your example is the invocation of the configuration which
creates the MOF file.  That should not be part of your configuration,
especially if you have parameters.  The configuration template is separate
from the compiled configuration. When you are generating the MOF for Azure,
Azure itself is invoking that last line in your example.

Remember that there are threr phases here:
1. Define the shape of the system in a configuration file
2. Create a specific configuration for the system(s) you are targetting
3. Validate and/or apply the configuration to the system

Consider a File DSC object.  The way it gets described to DSC is standard,
this is the config. The way it should look on the target host, this is is
the MOF. And finally, the actual bits and bytes of the actual file is the
actual configuration.

Scottley


On Aug 16, 2017 6:46 AM, "Alex SaPozhkov" <notifications@github.com> wrote:

Is there a proper approach for compiling the same document in both Azure
and PowerShell?

When I create a DSC configuration document, the only way compile it by
running one command that I know of is adding a line for calling the
configuration function itself, like this:

Configuration SP2013EntDevEnv
{
...
}
SP2013EntDevEnv -ConfigurationData $configurationData

At the contrast, if I want to feed my ps1 to the ARM, I have to remove this
last line so that Azure does not reject it.

So as I can see it now, there is no proper way of developing only one
document that I can use from time to time in PowerShell or Azure. Unless I
don't know how to do it right.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PowerShell/DscResources/issues/308>, or mute the thread

**Comment by shurick81** [comment]
Hello Scottley. Thank you for the confirmation that I did it wrong with the last line in the file. But how can I invoke this function using my PC with PowerShell if I don't have this line in ps1 file. Is there some PowerShell command like "Compile-DSC myconfig.ps1 -ConfigurationData $cd"?

**Comment by scottleyg** [comment]
Dot source the config file, this brings the functions into scope:
. <path to dsc config file>

The above is hard to read, but if i was speaking it, i would say, "dot
space path to file"

Then just Invoke configuration functions with desired parameters.
Scottley

**Comment by shurick81** [comment]
Thanks again Scottley, this worked like a charm
