### ISSUE TITLE
MSFT_RegistryResource Rewrite how to load

### ISSUE THREAD

**Issue by TofuBug** [PowerShell/DscResources#331]
Long explanation to lead into a question please bear with me

Converted the MSFT_RegistryResource into a PowerShell Class based DSCResource (technically 2)

Additionally converted CommonResourceHelper.psm1 to a PowerShell Class based module as well

Made a few modifications including:

- 2 Dsc Resources

  - XRegistryKey (Class Based DSC Resource) [Changes Below]
    - Moved LocalizedData as a Static property in xRegistryKey class
      - No need to create this data more than once, rest of class just references the static property
    - Separate Hive property (Key Property along with the Registry Key Key property)
      - (removes the need to parse out the "drive" from the key, while also simplifying the split and parsing of the Key property 
      - Hive Property is Typed off a custom Enum based on RegistryHive Enum (limiting to only applicable Hives in Windows 10)
    - Extensive simplification of logic especially validation logic
      - This resource only deals with creating and deleting Registry Keys  allowing me to for go
        - Parsing Drive and converting back and forth from a hash table
        - Several Null Verifications as the DSC Resource will not run unless all key and mandatory properties are provided

  - xRegistryValue (Class based DSC Resource inherited from xRegistryKey Above) [Changes below]
    - ValueType is typed off of a custom Enum based on RegistryValueKind (limiting values to one we wish to work with)
      - ValueType is now REQUIRED for this resource
    - ValueName is now the third key along with xRegistryKey's Hive and Key properties
    - implicitly inherits the keys and requirements from xRegistryKey Class
      - Utilizing the logic defined in xRegistryKey class the Test, Set, and Get methods of xRegistryValue are greatly simplified
        - e.g. If ([xRegistryKey]$this.Test()) returns true then for [Ensure]::Absent xRegistryValue MUST be test true also, or conversely if ([xRegistryKey]$this.Test()) returns false and [Ensure]:Present, xRegistryValue MUST test false also
          - In both cases if the Key does not exist implicitly the Value cannot exist meaning there is no need for additional validation logic in these cases

- For both Resource above several support functions in the original MSFT_RegistryResource.psm1 are no longer used and have been dropped including
  - Get-PathRoot
  - ConvertTo-RegistryDriveName
  - Get-RegistryDriveName
  - Get-RegistryKeyName

- Additionally for both resources above all Methods that are not Test, Get and Set are marked as hidden
- Additionally since these are methods of a class they require a much smaller set of parameters than their MOF file based Resource

I'm sure there are other items I've changed that i'm not thinking of but that's the brunt of it

The problem i'm running into is I've "tested" it by manually running it in several scenarios and manually verifying its operation, but I was ready to move on to writing some pester test for it (more to the point adopting and modifying the existing pester tests that already exist in the PsDscResources)

The problem is If i pull out my version of MSFT_RegistryResource and drop its folder in the root of C:\Program Files\WindowsPowerShell\Modules\ (With some obvious modificiations in my psd1 file for the location of CRHelper.psm1 (Class based version of CommonResourceHelper.psm1) `Get-DscResource -verbose` will happily find and pull in both classes as valid DscResources and writing a Configuration it picks up on the Enums, Shows red when properties are required (INCLUDING inherited key and mandatory properties)

But I can NOT for the life of me get Get-DscResource to pick up the two new class resources if i put it back into the original spot under the DscResources folder of PSDscResources module it's like Get-DscResources ONLY looks for mof based modules and skips right over the class based ones

I REALLY wanted to be able to work on my pester tests in the context of MSFT_RegistryResource being PART of PsDscResources.

**Comment by johlju** [comment]
We gave it a try to implement a class based resource over at xSQLServer. But the lack of a good way of testing it currently (also discussed it over at the Pester repo), and that the work making classes better is on hold until a later PowerShell version, we gave it up and converted the resource to mof based. 

Here is the discussion, maybe it helps in any way:
https://github.com/PowerShell/xSQLServer/issues/673

**Comment by TofuBug** [comment]
@johlju 

I rewrote it because I have a specific edge case I needed to fill so I figured instead of writing my own registry resource i'd tear down this one so I understand how it works and put it back together (With the added bonus of seeing how far I can go with PowerShell Classes)

REALLY hope things get figured out on the Pester side of things, Writing these DSC Resources MOF style is ALMOST physically painful after you've experienced writing them with Classes.

**Comment by TofuBug** [comment]
@johlju 

So riddle me this:

You can write Class based DSC Resources 

BUT...

you SHOULDN'T??? because there is no way to unit test them.

I'm admittedly not the most knowledgeable when it comes to unit testing it seems that the biggest hold ups are the potentially stale nature of classes which can be worked around running pester as a job so you get a fresh session each time. And the other is the lack of pester support for Mocking objects.

You can use New-MockObject but that creates an object uninitialized by a constructor, no way to actually mock the methods or properties inside the class.

But what about using just plain old inheritance and take advantage of how powershell's classes work when inheriting namely that to override a method in a base class ALL i have to do is write a method with the same name and method signature in the derived class? (no need for abstract, virtual, or override keywords)

i.e consider the following simple example

```PowerShell
Class Real {

    [bool] $Good
    
    [bool] DoesSomethingRealAndReturnsBool() { return $this.Good }

    [void] DoesSomethingWithABoolAndDoesSomethingReal() {
        if ($this.DoesSomethingRealAndReturnsBool()) {
            ...
        }
    }
}
```

Then we do this

```PowerShell
Describe 'Class Test' {
    class MockReal : Real {
        # Override method to return what we want
        [bool] DoesSomethingRealAndReturnsBool() { return $true }
    }

    it 'Should return true' {
        $Mock = [MockReal]::new()   
        $Mock.DoesSomethingRealAndReturnsBool() | Should be $true
    }
}
```

Is that considered a VALID test? is simple inheritance a good enough stand in for full object Mocking to consider the behavior of the base object as TESTED?

Because if that's the case I can work with that until pester figures out a way to fully mock objects.

**Comment by randomnote1** [comment]
Hi @TofuBug! Since I was the one who sent @johlju down the path of the class-based resource, I figured I'd weigh in with my knowledge.

The method you described by creating a mock class is exactly how I went about it. This has been something we've been using even with the MOF-based resources. This in of itself works great!

The issues we saw were:
- When the unit tests were executed locally, the tests would work once per session. If the tests were executed a second time in the same session, they all would fail. Per @johlju's notes, this problem was resolved in the PowerShell 6 beta.
- The tests for the module would work in AppVeyor, but caused other tests to fail.
- Referencing more than 1 class-based resource in the base module may be problematic. I was only able to get it to work by referencing the class-based resource directly. This would be a problem as soon as the 2nd class-based resource is added.

I haven't looked at these issues since July, so there's a possibility things may have changed. Take a look at [this branch](https://github.com/PowerShell/xSQLServer/tree/test-problem-class-based-resource-issue-%23673) to see what our attempt looked like. Long story short, we'd love to get everything working for class-based resources!

**Comment by TofuBug** [comment]
HI @randomnote1!!!

Some follow up questions then

The issues we saw were:

> - When the unit tests were executed locally, the tests would work once per session. If the tests were executed a second time in the same session, they all would fail. Per @johlju's notes, this problem was resolved in the PowerShell 6 beta.

When exactly IS Powershell 6 going to be officially available is there any kind of time table (lol I ASSUME there is the question should be is where can i read up on that)

> - The tests for the module would work in AppVeyor, but caused other tests to fail.

Are we talking tests in the same Tests.ps1 file? other tests later down the line? 

I'm really not sure about AppVeyor, I mean I know WHAT it is but I have not had the opportunity to use it I've been TRYING for about a year now to convince the powers that be to let me implement a CI/CD system but I work for a government agency and they REALLY do not like

1. external systems holding on to and manipulating data

2. change

So right now i'm piloting local server installs on my own of an atlassian set of products (BitBucket, Bamboo, and SourceTree, not sure about the name of that last one) which so far has been pretty useful for the $10 total price tag (it's just me and 3 other guys managing this stuff)

That being said my trial has long since expired and i'm waiting for my management to convince upper management that a CI/CD system is REALLY in our best interest even at $10 it seems to be a stuggle to convince them

> - Referencing more than 1 class-based resource in the base module may be problematic. I was only able to get it to work by referencing the class-based resource directly. This would be a problem as soon as the 2nd class-based resource is added.

Do you mean referencing them in the same .Tests.ps1 files or in DSC itself?

I had not gone down the road of writing my tests in the manner you just confirmed for me is valid "mocking", for the simple reason of not wanting to waste time going down the wrong path, BUT I have done my own manual tests with DSC itself and I can push and run a DSC configuration using both of my class based RegistryKey and RegistryValue DSC Resources with zero issues so far. Have NOT tried it on my pull server yet wanted to get things like unit tests ironed out first

Finally I still think I would like to offer up the attempt I made to write this resource as classes even though the testing part is still not 100% with the understanding that until that does get resolved it can't really be used. My question is should I submit it under the branch you linked above? I'm SO used to working on my own (I only JUST recently got my manager to give me even a small team of people to help me) so i'm behind the 8 ball on really utilizing things like github. 

So when classes are finally testing reliably does this github project pickup back over at the branch where the attempt at class based resources left off, does it start from the current branch and the classes are redone from scratch?

Sorry for all the questions, and thanks a ton for the insite

**Comment by randomnote1** [comment]
@TofuBug, first I'd like to welcome you to the wide world of open source! I myself have only started contributing in the last year, so I understand how steep the learning curve is. We'll do our best to guide you through!

Here's some reading about the future of [PowerShell](https://blogs.msdn.microsoft.com/powershell/2017/07/14/powershell-6-0-roadmap-coreclr-backwards-compatibility-and-more/) and [DSC](https://blogs.msdn.microsoft.com/powershell/2017/09/12/dsc-future-direction-update/). Long story short, all development efforts are on PowerShell Core which is the cross-platform version of PowerShell. According to the article, Windows PowerShell will not receive any new features. Therefore, I think it's unlikely that Windows PowerShell will receive a new major version.

> Are we talking tests in the same Tests.ps1 file? other tests later down the line?

These are tests down the line. Since the Availability Group resources fall at the beginning of the alphabet, the cascading failures were ugly.

AppVeyor is simply a server that gets some scripts run on it. It ultimately calls Pester which runs through all of the unit and integration tests specified in the module.

> Do you mean referencing them in the same .Tests.ps1 files or in DSC itself?

I believe the references were in the `xSQLServer.psd1` file. I went through a lot of iterations on this one, so I don't recall what actually worked.

I'll let @johlju make the call on how to proceed with the resource since he is the maintainer. What happened in the case of xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership was that I re-wrote the resource as a MOF-based resource. It was blocking the release of the module as a class-based resource, and I needed the functionality. We kept the branch around for testing in the future, but I don't know that we've wrapped back around to it.

**Comment by johlju** [comment]
@TofuBug First, as @randomnote1 did, I would also like to welcome you to this amazing community! Thanks for using and working on DSC!

Please read this discussion here as well https://github.com/pester/Pester/issues/797 where it's hinted  that some issues with class-based resources are moved to PowerShell 6.1.

Here are my thoughts, if I misunderstood anything then I apologize in advance.

I think you are suggesting that you want to submit the resource you converted from MSFT_RegistryResource (originally from PSDscResource)? We certainly appreciate your work, and as @randomnote1 says, we would love for class-based resource to work. That said, since the resource you are working on aren't SQL Server resources submitting them to the xSQLServer repository would not be suitable. I could not accept them.
If you want to submit the converted resources, then you could open an issue in the PSDscResource repository asking if they want to replace the resources with yours, but for them to go with the idea, in my honest opinion, the resources must add more value and have proper testing.

If you just want to test your converted resources they way we do. Then you can create your own repository in your GitHub account, then you can copy the entire contents of PSDscResource into your newly created repository. From there you can strip away all the resources and tests (and other stuff you don't need), and then add your class-based resources. Connect the repository to your AppVeyor account and then you will have the correct test framework to run tests when you push changes to your repository. You of course need to write tests for the class-based resource for them to be tested. But if you keep one of the originally resources (with it's corresponding tests) you can verify that the test framework work.

The branch `test-problem-class-based-resource-issue-#673` in xSQLServer repository contains how the class-based resource looked like before converting it to MOF-based. I saved the branch to be able to test if there are improvements in PowerShell that will make class-based resource "work better". If you would like to continue the work on the branch `test-problem-class-based-resource-issue-#673` you are welcome to do so. You can fork the repository xSQLServer to your account, and you can create a AppVeyor account and connect the fork to AppVeyor. I then suggest you create a working-branch based on the branch `test-problem-class-based-resource-issue-#673`. You then push your working branch to your fork, and for each push the tests will run in AppVeyor (you can see the tests running in your AppVeyor account).
Note that the above branch that holds the class-based resource will be deleted when I don't see a point of keeping it any longer. The class-based resource is already far behind the Mof-resource in functionality. 
Also, I'm not seeing us (in xSQLServer) converting Mof-based resource to class-based resource unless there is a big benefit to do so (which it probably will be), or that we must convert because that is were PowerShell/DSC is moving.

Finally. I you did not get a question answer, let us know. :smile:

**Comment by TofuBug** [comment]
ok @johlju  and @randomnote1 

I've got me an AppVeyor account, cloned over the PsDscResources module to my own repository

But the VERY first build in AppVeyor before i made any changes fails with

```
[-] Should contain a PowerShellVersion property of at least 4.0 based on resource types 1.02s
      PropertyNotFoundException: The property 'PowerShellVersion' cannot be found on this object. Verify that the property exists.
      at <ScriptBlock>, C:\projects\psdscclassresources\DscResource.Tests\Meta.Tests.ps1: line 300
```

and then

```
Executing script C:\projects\psdscclassresources\Tests\Unit\ResourceSetHelper.Tests.ps1
  [-] Error occurred in test script 'C:\projects\psdscclassresources\Tests\Unit\ResourceSetHelper.Tests.ps1' 52ms
    RuntimeException: Multiple Script modules named 'ResourceSetHelper' are currently loaded.  Make sure to remove any extra copies of the module from your session before testing.
    at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.8\Functions\InModuleScope.ps1: line 115
```

Seems the first one is referencing a completely different github repository DscResource.Tests. Am I supposed to clone that one as well to my repository so I can make the corrections so it builds successfully in AppVeyor?

I apologize for the continued content in this thread if I could figure out how to PM either of you with my general questions I'd rather do that than take up space on what should be a thread to discuss issues with the repository

At this point I just want to get it to successfully build once so I have a baseline to work from as I start to experiment with modifying things

Thanks again for all the help so far

**Comment by johlju** [comment]
Make sure you change any references of 'PSDscResources' to your new repository name (filenames and in code).
The first error you are getting is because the .psd1 file is not named equal as the repository name (the test framework expect that). 
For the second error, fix all references for 'PSDscResources' to your new repository name in the code, for example the integration tests reference the PSDscResource repo. See if that resolves the issue. 

DscResource.Tests is the test framework that runs all common tests and runs your repos test. You don't need to clone DscResource.Tests (if you want to improve the tests for the DSC community then you fork this repo, and push changes to PowerShell Team's main repo). 
It's cloned into the repository folder if a test is run locally. For AppVeyour it's cloned as one of the first steps (see the appveyor,yml which is the config file for what AppVeyor build worker is run and how the build/tests is run).

Don't worry about these kind of questions. I think one focus of this repo should be to onboard new contributors to be able to contribute to DSC. That said, if you feel like you this issue is moving out of scope, since you have your own repo for this, you could start an issue in your repo and tag me (@johlju) and other to ask for help, We should get an e-mail when you tag us, and the community will help if they can.

**Comment by TofuBug** [comment]
@johlju 

THANK YOU!!!

That did the trick i'm off to the races now

I'll probably be back to bug you guys again down the road but for now hopefully i can go on my own for a while

Thanks again for the help

**Comment by johlju** [comment]
@TofuBug Can we close this issue now?

**Comment by johlju** [comment]
Closing this as solved as per author comment. Please reopen or comment if this was closed in error.
