### ISSUE TITLE
Style Guidelines for Class bases DSC resources

### ISSUE THREAD

**Issue by TofuBug** [PowerShell/DscResources#332]
Running a fork of this,repo through it's paces and I've noticed that for the modules I've converted from functions to classes the PsScriptAnalyzer part of the test is complaining about the method signatures namely 

A [Parameter()] attribute must be the first attribute of each parameter and be on its own line. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

The problem is Attributes are not valid in methods of classes you have to put them with the properties of the class.

I read through the style guidelines and can't find anything related to classes

Just curious if there are plans to update the custom PsScriptAnalyzer rules to include Classes

**Comment by johlju** [comment]
When writing those we did not take in account class-based resource. Either the custom analyzer rules must handle class-based resource, or those tests are not run on the class-based resource in the DSCClassResources folder. making the custom analyzer rules handle classes would be best. 

Since there are no class-based resource in the Dsc Rsource Kit yet, there are not much guidelines around that.

Please submit an issue to https://github.com/PowerShell/DscResource.Tests/issues that the custom analyzer should be class-based resource aware. If you feel like resolving the issue, since you have the class-based resource to test on, then please send in a PR to DscResource.Tests.

**Comment by johlju** [comment]
@TofuBug since PR https://github.com/PowerShell/DscResource.Tests/pull/200 was merged, is this solved so we can close this issue?

**Comment by TofuBug** [comment]
Yeah sorry i've been buried in work so I haven't had a chance to pop back on here.

Go ahead and close it out :-)

**Comment by TofuBug** [comment]
Or do i have to close it

**Comment by johlju** [comment]
@TofuBug Please close if you have time, otherwise I will close it as soon as I get the required permission in this repository. :)
