### ISSUE TITLE
There are no guideline for when to use single quotes and double quotes

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResources#335]
When doing review I always enforced the use of single quotes instead of double quotes around strings when there is no variable to evaluate in the string. But I realized now that there are actually no specific guideline around that in either StyleGuidline.md or BestPractices.md. 
All other guidelines do use single quotes around strings, so probably from there I have picked it up and started to enforced it (and probably because that is the way I code by default).

I suggest we should add a guideline in BestPractices.md saying that using double quotes around strings should be avoided where possible.

**Bad:**
`"String that do not evaluate variable"`

**Good:**
`'String that do not evaluate variable'`

**Good:**
`"String that evaluate variable $($SomeObject.SomeProperty)"`

Anyone has thoughts on this?

**Comment by PlagueHO** [comment]
:+1: for me. I've been enforcing this and not realizing that it isn't actually in the best practices. :grin:

**Comment by BrianFarnhill** [comment]
Personally as long as its functional code, I'm way less concerned about the types of strings. I know we get pretty pedantic on styling guidelines sometimes and for me personally, this one I don't care about too much.

**Comment by BrianFarnhill** [comment]
I won't argue the performance point - but let me give you some perspective that relates specifically to my module SharePointDsc. Right now, our module has around about 100 different DSC resources in it. Last time a change for style rules got made and put into the tests we then got pretty much forced to immediately go and make the changes to our 100 files to line up with it so that the tests would pass. I get this might be an easy to implement change in some other resources, but I can tell you right now between the main module and the unit tests we have in SharePointDsc this would create hours and hours of work for either myself or one of our contributors to get things sorted again. And for what benefit? Yes, it would perform a tiny fraction of a second better, but even if you added up all of those fractions of seconds from everyone who runs our resources across the world, it likely wouldn't add back up to the time it took to get the change done in the first place (or at best, it would take quite some time to do so). 

I'm all for documenting the best practices where they will genuinely make a difference to the readability of a script, or a noticeable difference in performance, or any number of other reasons. But this one in particular from where I stand won't justify the effort to retrofit the change into the modules.  Based on that, I really don't think it's worth enforcing.

**Comment by tysonjhayes** [comment]
I'm going to echo that this should probably a best practice (I'm not sure on how much of a performance improvement there is or if that's just been repeated enough where we think the is some merit). However, I see no need in retrofitting existing code to comply.

**Comment by randomnote1** [comment]
Yes, I totally agree that it should be written as best practice, but not required. There's no reason to retrofit existing code.

@tysonjhayes, I did some testing across a couple laptops to confirm that the performance benefit was still a real thing. It's still faster to use single quotes than double. The bigger item to look at is the methods used to populate variables in a string. It appears that using the fill (`-f`) operator is the fastest way to populate variables in a string. I'll try to publish my results when I have some more to share.

**Comment by PlagueHO** [comment]
I'm definitely not keen to retrofit all modules for single quotes, but if I'm making changes to meet HQRM I generally try to include changing double quotes to single wherever possible. I also tend to prefer `-f` for string formatting so it is good to know that this is the most performant method. I'm some cases stringbuilder should probably be used though.

**Comment by johlju** [comment]
The reason I try to enforce this is so we get code that looks the same.

The discussion seem to lean towards adding this as a best practice. But as several had said, there is no need to change existing code.
