### ISSUE TITLE
[File] resource needs to have an option to set encoding

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/DscResources#344]
Hello,

Currently DSC [File] resource by default saves file in UTF8-BOM encoding and there is no way to set it inside resource. This breaks bunch of things in certain scenarios. Please add that feature.

**Comment by johlju** [comment]
We have no way of changing that resource here on GitHub as it is not part of the DSC Resource Kit, it is a built in resource in Windows PowerShell Desired State Configuration. But we could create an issue with a new resource proposal in PSDscResources.

@kwirkykat do you have any more insights on how to resolve issues in the built-in resources?

**Comment by johlju** [comment]
If your proposal is to extend the builtin File resource, then I suggest you [add your proposal as a uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/?query=File%20resource), if it doesn't already exist, so that you can track it and other users can vote on it.

Or you can propose a new resource in the repository [PSDscResources](https://github.com/PowerShell/PSDscResources) that will include this suggestion.

I'm closing this issue at this time since we can't do anything more about it in this repository.
