### ISSUE TITLE
unable to download a exe from azure file storage in azure automation as well as in local pull server setup

### ISSUE THREAD

**Issue by sivajibhai** [PowerShell/DscResources#350]
Iam trying to download a file from network shared path from azure file storage. For that i tried with below script but not success. can you support on this issue
Script i tried. Even i tried using SAS. 
configuration copymsi
{
    Import-DscResource -Module xPSDesiredStateConfiguration
Node "localhost"
{
    xRemoteFile Download
    { 
       Uri = 'https://devopsdiag299.file.core.windows.net/'
       DestinationPath = 'C:\Users\devopsuser1\Documents\npp.7.5.5.Installer.exe'
   }
}
} 
the Error it shows like this
Error: PowerShell DSC resource MSFT_xRemoteFile failed to execute Set-TargetResource functionality with error message: Invoking web request failed with error 400: Value for one of the query parameters specified in the request URI is invalid.

**Comment by johlju** [comment]
For that to work the file must be publicly available, is it? You don't have to logon to the storage account to access the file? Maybe you have obfuscated the path above, because it should also contain the container and the file to download?

See if this helps [DSC resource to copy files from Azure file storage](https://social.msdn.microsoft.com/Forums/azure/en-US/ab6a7c0f-64f7-45d8-b20e-afb21bd818cd/dsc-resource-to-copy-files-from-azure-file-storage?forum=windowsazuredata).

**Comment by johlju** [comment]
Also see @BrianFarnhill's repo [xAzureStorage](https://github.com/PowerShell/xAzureStorage/wiki/AzureBlobFiles) if it could help.

**Comment by johlju** [comment]
Closing this as solved as per previous comment. Please reopen or comment if this was closed in error.
