### ISSUE TITLE
There is no guideline for handling output to $null

### ISSUE THREAD

**Issue by ld0614** [PowerShell/DscResources#383]
While reviewing a PR for xRemoteDesktopSessionHost I noticed that the contributor was using the form `$null = $PSBoundParameters.Remove('EnableUserProfileDisk')` to discard output, personally I would have written the code as `$PSBoundParameters.Remove('EnableUserProfileDisk') | Out-Null` as I think its clearer however I couldn't see an existing style guideline for this scenario.  

What are other peoples thoughts?

**Comment by PlagueHO** [comment]
Hi @ld0614 - I think this question has come up elsewhere. I used to use the ` | Out-Null` format myself until one of the members of the PowerShell team pointed out to me (a few years ago now) that the `$null = ` actually performs better as it doesn't have the overhead of setting up the pipeline. So I've used the `$null = ` assignment ever since. But this might have been improved in PowerShell at some point.

I'm not sure if this has ever been formalized into a best practice though for DSC resource kit.

**Comment by ld0614** [comment]
Thanks for the info @PlagueHO running the following commands 
`Measure-Command {
    for ($i = 1; $i -lt 9999; $i++)
    { 
        'Some Text' | Out-Null
    }
}

Measure-Command {
    for ($i = 1; $i -lt 9999; $i++)
    { 
        $null = 'Some Text'
    }
}`

Gave 1826.1557 and 64.5673 milliseconds respectively.  Considering the massive performance difference I'd propose still writing a style guideline but for moving everything to $null = from Out-Null

**Comment by PlagueHO** [comment]
@ld0614 - FWIW, on PowerShell Core 6.0.1:
78.53 ms
18.6923 ms

So clearly the PS Team has done some great stuff in this area. Still slower, but much less so.

@johlju - should there be a guideline added?

**Comment by johlju** [comment]
In PowerShell 5.1.17672.1000 the difference is (`Out-Null`) ~200 vs (`$null`) ~10. Running the above in PowerShell 6.0.2 `$null` is still ~75% faster. Looping through 2 items using the above code there are no difference.
Nevertheless, either way of writing this should be okay. If looping through 10000 objects and need that millisecond speed increase then I think one can consider using on or the other. 😃

**Comment by PlagueHO** [comment]
I agree - it is pretty negligible, but it does add up, especially when lots of resources use it a lot (for example Firewall in NetworkingDsc has a few loops that use it) and you have large configs. It is one of those performance things that on it's own isn't a big issue, but is something we should try to consider.

**Comment by johlju** [comment]
In regards for speed I don't feel there is need for a guideline around this when there is no difference using either for the purpose of what this usually is used for, discarding output from one call. 
We could add a best practice saying that "if performance is necessary, consider using `$null` instead of `Out-Null` if `$null` performs better".

**Comment by johlju** [comment]
Using this gives so little difference, and sometime `$null` is slower.

```
Measure-Command {
    for ($i = 1; $i -lt 2; $i++)
    { 
        'Some Text' | Out-Null
    }
}

Measure-Command {
    for ($i = 1; $i -lt 2; $i++)
    { 
        $null = 'Some Text'
    }
}

```

**Comment by PlagueHO** [comment]
It probably isn't going to be worth the guideline. I'd just suggest that the style that is adopted is what ever the destination repo uses.

**Comment by johlju** [comment]
I agree.

**Comment by johlju** [comment]
@ld0614 appreciate you raising the issue! Always good to discuss! 🙂

**Comment by bilbothebaggins** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/powershell/script-authoring-considerations#suppressing-output

**Comment by PlagueHO** [comment]
@bilbothebaggins - I've adopted `$null = ` in all the repositories I maintain. But many maintainers have not. I've seen `[void]` in a couple, but most are using the less performant `| Out-Null` method.

I'd be OK with adding a recommendation to adopt `$null = ` (or even [void] assignment), but I doubt we'd be able to enforce an HQRM rule. @johlju, @gaelcolas?

**Comment by johlju** [comment]
It is the "It should be avoiding in performance sensitive code." thats important here. If you use `| Out-Null` when looping through a few thousand iterations another method might be faster. But using it with a few calls every 15 minutes which is normal for a DSC resource it doesn't make a measurable difference?
Also, in PS Core the difference have been removed so even for a few thousand iterations (at least that what I read a while back) `| Out-Null` should bed equally fast. 

If we should add a guideline, the it should be enforced otherwise there is no need for a guideline. A recommendation is already in that article that is referenced above, so contributors and maintainers can use it and enforce it per individual repo. Currently I will allow either method in those I maintain, up to the contributor to choose the best for each scenario.

That said, if the community is strongly towards `$null` then I suggest adding that to a guidline so it can be enforced by a PSSA custom rule,

**Comment by PlagueHO** [comment]
I'm good with just adopting a per repository preference.

**Comment by andikrueger** [comment]
From a DSC contributor perspective and as someone, who struggled with this topic before: I would prefer to have a documented quasi-standard (`$null=`) outside of this discussion and within the guidance or at least a visible link to the mentioned docs article (see: https://github.com/PowerShell/DscResources/issues/383#issuecomment-538307996)
