### ISSUE TITLE
New resource module submission: xAdfs

### ISSUE THREAD

**Issue by jonathaneckman** [PowerShell/DscResources#417]
### New resource module submission

**Name:** xAdfs

**Repository URL:** [https://github.com/jcwalker/xAdfs](https://github.com/jcwalker/xAdfs)

**Short description:** Configures ADFS.

This is another Microsoft repo managed by @jcwalker, not my own, but would like to recommend it for the Dsc Resource Kit.

**Comment by johlju** [comment]
Would be great to add this a new module submission, but we need the owner to make a new module submission since there are a few prerequisites that need to be in place. See https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md

I suggest you open an issue in the owners repository asking the owner to make a new module submission. 

I’m closing his issue at this time. Thanks for suggesting this though!
