### ISSUE TITLE
StyleGuidelines.md: Style guidance for parameter usage in function and cmdlet calls

### ISSUE THREAD

**Issue by mhendric** [PowerShell/DscResources#446]
Is there any style guidance for how best to pass parameters to functions and cmdlets? If not, is this something that should be added? Things I'm thinking of are:

-Do we allow both single line and multi line passing of parameters? Do we prefer one over the other?
-If multi line is allowed, what are our best practices for formatting the passed parameters?
-Do we care about inline array or hashtable declarations, or do we want them assigned to a variable before passing?

**Comment by PlagueHO** [comment]
Hi @mhendric,

There are some styleguidelines for this:

- There isn't a style guideline on this (there probably should be), but we do allow both single line and
  multi-line parameters. But the rule of thumb is that if a line gets beyond 80 chars then it should be split.  
  This used to be a style guideline but it got removed sometime back.
- Multi-line is enabled but there isn't a styleguideline for formatting - although we do tend to apply
  [Correct Format for Long Function Calls](Correct Format for Long Function Calls)
- We do if there are lots of parameters - but there isn't a hard rule as to how many. I usually apply the line length 80 max - and if the line hits that I'll use a splat or multi-line parameters. See this rule [Correct Format for Long Function Calls](Correct Format for Long Function Calls)

@johlju - sounds like a bit more guidance around this area could be needed.

One final thing, my general rule of thumb if I'm contributing to one of these projects and there isn't a specific style rule is that I'll do my best to copy the existing code.

**Comment by johlju** [comment]
Personally I tend to use splatting when the lines start to move over ~80 chars. I actually have a ruler in VS Code just for this. 
```
"editor.rulers": [
        80
    ]
```

The guidelines that I know of.
* Use splatting for long calls [Correct Format for Long Function Calls](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-long-function-calls)
* Use named parameters [Named Parameters Instead of Positional Parameters](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#named-parameters-instead-of-positional-parameters)

But I have seen these variants. 

Suggestion of what I think is good and bad, please comment on that. Also, please add any variants that I missed.

#### Variant 1 - Good ✔️
```powershell
$superLongVariableName = Get-MyVariablePlease -MyStringParameter '123456789012349012345678901234567890' -Verbose
```

#### Variant 2 - Good ✔️
```powershell
$superLongVariableName = Get-MyVariablePlease -MyString1 '1234567890' -MyString2 '1234567890' -MyString3 '1234567890' -Verbose
```

#### Variant 3 - Good ✔️
The call is long, and will probably wrap when viewing it during the review. But still it should be allowed (?).

```powershell
$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'
```

#### Variant 4 - Good ✔️

```powershell
$mySuperLongHashtableParameter  = @{
    MySuperLongKey1 = 'MySuperLongValue1'
    MySuperLongKey2 = 'MySuperLongValue2'
}

$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongHashtableParameter $mySuperLongHashtableParameter -Verbose
```

#### Variant 5 - BAD ❌
The call is very long, and will wrap a lot when viewing it during the review.

```powershell
$mySuperLongHashtableParameter  = @{
    MySuperLongKey1 = 'MySuperLongValue1'
    MySuperLongKey2 = 'MySuperLongValue2'
}

$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongHashtableParameter  $mySuperLongHashtableParameter  -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' -Verbose
```

#### Variant 6 - BAD ❌
Hashtable is not following [Correct Format for Hashtables or Objects](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects).
```powershell
$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongHashtableParameter @{ MySuperLongKey1 = 'MySuperLongValue1'; MySuperLongKey2 = 'MySuperLongValue2' } -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' -Verbose
```

#### Variant 7 - Good ✔️
Splatting all parameters.

```powershell
$getMySuperLongVariablePleaseParameters = @{
    MySuperLongHashtableParameter = @{
        MySuperLongKey1 = 'MySuperLongValue1'
        MySuperLongKey2 = 'MySuperLongValue2'
    } 
    MySuperLongStringParameter = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' 
    Verbose = $true
}

$superLongVariableName = Get-MySuperLongVariablePlease @getMySuperLongVariablePleaseParameters
```
#### Variant 8 - BAD ❌
Hashtable is not following [Correct Format for Hashtables or Objects](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects).

```powershell
$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongHashtableParameter @{ MySuperLongKey1 = 'MySuperLongValue1'; MySuperLongKey2 = 'MySuperLongValue2' } `
                                                       -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' `
                                                       -Verbose
```
#### Variant 9 - Good ✔️
Good, but using auto formatting in VS Code will mess this up (?).
```powershell
$superLongVariableName = Get-MySuperLongVariablePlease -MySuperLongHashtableParameter @{
                                                            MySuperLongKey1 = 'MySuperLongValue1'
                                                            MySuperLongKey2 = 'MySuperLongValue2' 
                                                        } `
                                                       -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' `
                                                       -Verbose
```
#### Variant 10 - BAD ❌
Hashtable is not following [Correct Format for Hashtables or Objects](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-hashtables-or-objects).

```powershell
$superLongVariableName = Get-MySuperLongVariablePlease `
    -MySuperLongHashtableParameter @{ MySuperLongKey1 = 'MySuperLongValue1'; MySuperLongKey2 = 'MySuperLongValue2' } `
    -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' `
    -Verbose
```
#### Variant 11 - Good ✔️
```
$superLongVariableName = Get-MySuperLongVariablePlease `
    -MySuperLongHashtableParameter @{
        MySuperLongKey1 = 'MySuperLongValue1'
        MySuperLongKey2 = 'MySuperLongValue2' 
    } `
    -MySuperLongStringParameter '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' `
    -Verbose
``` 
#### Variant 12 - BAD ❌
Passing parameter (`Verbose`) outside of the splat.

```powershell
$getMySuperLongVariablePleaseParameters = @{
    MySuperLongHashtableParameter = @{
        MySuperLongKey1 = 'MySuperLongValue1'
        MySuperLongKey2 = 'MySuperLongValue2'
    } 
    MySuperLongStringParameter = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'
}

$superLongVariableName = Get-MySuperLongVariablePlease @getMySuperLongVariablePleaseParameters -Verbose
```

**Comment by mhendric** [comment]
Thanks guys. Regarding the 80 character (suggested) limit, is that from the start of the line, or from the first non-whitespace character?

**Comment by johlju** [comment]
I count from the start of the line, but there are okay to make it longer than 80 chars, there are occasions where I make longer lines too. :) So it’s good you think of it as a suggested limit and not a hard limit.

**Comment by johlju** [comment]
I make a PR with these changes tomorrow, so you can review it.
