### ISSUE TITLE
We should add guidance on how to properly throw and test throws in resources. 

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResources#81]
Here is an example @tysonjhayes  gave in a review

> Instead of calling a throw here, can you use the following construct to throw the exception?
> https://github.com/PowerShell/xNetworking/blob/dev/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L708
> 
> I know this is a bit longer winded, but it creates a custom exception object that we can actually test for in unit tests.
> 
> So you'd end up with this:
> 
> ``` powershell
>         $errorId = 'TeamCreateError'
>         $errorCategory = [System.Management.Automation.ErrorCategory]::InvalidOperation
>         $errorMessage = $localizedData.failedToCreateTeam
>         $exception = New-Object -TypeName System.InvalidOperationException `
>             -ArgumentList $errorMessage
>         $errorRecord = New-Object -TypeName System.Management.Automation.ErrorRecord `
>             -ArgumentList $exception, $errorId, $errorCategory, $null
> ```
> 
> ``` PowerShell
>         $PSCmdlet.ThrowTerminatingError($errorRecord)
> ```

[Test Example](https://github.com/PowerShell/xNetworking/blob/dev/Tests/Unit/MSFT_xFirewall.Tests.ps1#L977):

``` PowerShell
            Context 'testing with firewall that somehow occurs more than once' {
                Mock Get-NetFirewallRule -MockWith { $FirewallRules }

                $errorId = 'RuleNotUnique'
                $errorCategory = [System.Management.Automation.ErrorCategory]::InvalidOperation
                $errorMessage = $($LocalizedData.RuleNotUniqueError) -f 2,$FirewallRule.Name
                $exception = New-Object -TypeName System.InvalidOperationException `
                    -ArgumentList $errorMessage
                $errorRecord = New-Object -TypeName System.Management.Automation.ErrorRecord `
                    -ArgumentList $exception, $errorId, $errorCategory, $null

                It "should throw RuleNotUnique exception on firewall rule $($FirewallRule.Name)" {
                    { $Result = Get-FirewallRule -Name $FirewallRule.Name } | Should Throw $errorRecord
                }
            }
```

**Comment by tysonjhayes** [comment]
I think some resources have functions that help make this a little better. [This](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/Helper.psm1#L11) comes to mind to at least reduce the amount of lines written. Though we could probably improve on it.

I'd love to see some standardization around error handling and testing so. :+1: to this. :grin:

**Comment by PlagueHO** [comment]
This get's my vote :smile:

**Comment by TravisEz13** [comment]
I'm planning on writing this.  I'll updating the guidance with the link @tysonjhayes provided.  I'll leaving it for feedback for a little while before I write it.  @KarolKaczmarek What do you think?

**Comment by KarolKaczmarek** [comment]
I agree it's a good practice and we should have guidance about it.

Was just wondering whether we should be adding it as best practice to the DSC documentation (https://github.com/PowerShell/PowerShell-Docs ) instead?

**Comment by johlju** [comment]
I don't think this has been documented yet.

The resource module xNetworking are using a helper function that builds an error record to test that the actual localized error is thrown. The resource module SqlServerDsc are using an alternate method in the tests, not building an error record but testing the correct localized error message is thrown.
I think either of these methods, or both, could be documented in the [Test Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) as the preferred method(s).

For example in xNetworking there are helper functions [New-InvalidOperationException](https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/Modules/NetworkingDsc.ResourceHelper/NetworkingDsc.ResourceHelper.psm1#L85) and [New-InvalidArgumentException](https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/Modules/NetworkingDsc.ResourceHelper/NetworkingDsc.ResourceHelper.psm1#L48) which are used in code to throw an error. 
To test that the actual error is thrown there are corresponding helper functions [Get-InvalidArgumentRecord](https://github.com/PowerShell/xNetworking/blob/dev/Tests/TestHelpers/CommonTestHelper.psm1#L11) and [Get-InvalidOperationRecord](https://github.com/PowerShell/xNetworking/blob/dev/Tests/TestHelpers/CommonTestHelper.psm1#L46) that builds the correct localized error message in the tests.

An example from xNetworking. Here the localized message NetAdapterNotFoundError is thrown.
```powershell
# Were any adapters found matching the criteria?
if ($matchingAdapters.Count -eq 0)
{
    New-InvalidOperationException `
        -Message ($LocalizedData.NetAdapterNotFoundError)


    # Return a null so that ErrorAction SilentlyContinue works correctly
    return $null
}
```
And the same localized message NetAdapterNotFoundError is tested.
```powershell
$errorRecord = Get-InvalidOperationRecord `
    -Message ($LocalizedData.NetAdapterNotFoundError)

It 'Should throw the correct exception' {
    { $script:result = Find-NetworkAdapter -Name 'NOMATCH' -Verbose } | Should -Throw $errorRecord
}
```

In SqlServerDsc there are a couple of more of these helper functions that throw an error; [New-ObjectNotFoundException](https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/CommonResourceHelper.psm1#L102) and [New-InvalidResultException](https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/CommonResourceHelper.psm1#L154)
In SqlServerDsc there are no helper functions that build the correct error record in the tests, the test of throwing of the correct localized message has been simplified.

An example from SqlServerDsc. This throws the localized error message in the code.
```powershell
else
{
    $errorMessage = $script:localizedData.DatabaseMailDisabled
    New-InvalidOperationException -Message $errorMessage
}
```

This tests so that the correct localized message is thrown.
```powershell
It 'Should throw the correct error message' {
    {
        Set-TargetResource @setTargetResourceParameters
    } | Should -Throw $script:localizedData.DatabaseMailDisabled


    Assert-MockCalled Connect-SQL -Exactly -Times 1 -Scope It
}
```
