### ISSUE TITLE
New resource module: AuditPolicyDsc

### ISSUE THREAD

**Issue by athaynes** [PowerShell/DscResources#86]
#### What system will your DSC resources be managing?

```
Windows Advanced Audit Policy
```
- [x] xAuditOption to manage audit policy options
- [x] xAuditCategory to manage Subcategory 'Success' and 'Failure' flags
- [ ] xAuditGlobalAccess to manage Registry and File system GlobalSACLs
#### Will your module include MOF-based resources or class-based resources

```
MOF-based resources
```

**Comment by athaynes** [comment]
repo link: https://github.com/athaynes/xAuditPolicy

**Comment by PlagueHO** [comment]
@KarolKaczmarek - would it help for some of us non-MSFT people to do a preliminary review on some of these new modules? E.g. to aid your team out a bit- obviously they'll still need a final review by your team, but we might be able to point out any glaring problems ahead of time and get the submitters to fix them up before you get to them? I'm happy to help out however I can.

**Comment by KarolKaczmarek** [comment]
@PlagueHO Definitely, if you are familiar with Windows Advanced Audit Policy, that would be greatly appreciated! We could later take care of reviewing the code against following DscResources guidelines etc., that's the easy part.

**Comment by PlagueHO** [comment]
@KarolKaczmarek  - Sure, I'm MCSA certified in Windows Server 2012/R2, so I know my way around it. :smile: I'll make a few comments here that @athaynes can fix before your team get to it (just a bit of tweaking on the test layout as far as I can see so far).

**Comment by KarolKaczmarek** [comment]
sounds great, thanks @PlagueHO!

**Comment by PlagueHO** [comment]
@athaynes: Nice work on the Repo! I just thought I'd give it a quick review to help out.

Just a few things you'll want to address:
- [ ] Unit tests: You've done a great job of implementing the tests, but are you able to move the tests into the actual templates you've created? E.g. Move the Describe blocks in https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/MSFT_xAuditCategory/MSFT_xAuditCategory.Tests.ps1 into the describe blocks of https://github.com/athaynes/xAuditPolicy/blob/master/Tests/Unit/MSFT_xAuditCategory.tests.ps1.
- [ ] Integration tests: you need to complete the TODO: sections in all the integration tests files (https://github.com/athaynes/xAuditPolicy/tree/master/Tests/Integration).
- [ ] Add an AppVeyor.yml file to the root of your repo (copy [this one](https://github.com/PowerShell/DscResources/blob/master/DscResource.Template/appveyor.yml) and modify to suit)
- [ ] Copy the Examples into the Examples section of Readme.md - suggest taking a look at the Examples section [here](https://github.com/PowerShell/xActiveDirectory/blob/dev/README.md#examples) for an idea of what they should look like.
- [ ] Helper.Tests.ps1 - could you move this file to the \Tests\Unit\ folder in your repo and adjust paths accordingly? Once again, fantastic test coverage!
- [ ] Move all examples to a folder called Examples in the root of the repo.

That's all I've got time to note tonight. But the core functionality looks really good (it's just a shame there isn't a native PS module to manipulate Auditpol). I'll continue the review tomorrow. Cheers

**Comment by athaynes** [comment]
@PlagueHO Thank you for the review. 

I am working on the recommendations you made and will have them up in a day or 2.

**Comment by PlagueHO** [comment]
@athaynes - no problem, sorry I haven't had a chance to complete the review yet. However, your Auditpol logic looks pretty sound so far. I'll try and finish the review today.

Thanks again! Great work BTW!

**Comment by athaynes** [comment]
@PlagueHO  I was out on vacation this week, but made the rest of the changes to get my test code in the templates and was hoping for one last quick review. Thanks.

**Comment by PlagueHO** [comment]
@athaynes - awesome! I'll do my best to get another review through this week (spending a bit of time myself trying to get my resources in order to get them accepted as well :smile: )

**Comment by athaynes** [comment]
@KarolKaczmarek, @PlagueHO  I just wanted to follow up to see if there was anything else I needed to do to my resource to move it to the next step. Thank you.

**Comment by PlagueHO** [comment]
@athaynes, I appologize I haven't completed a second review yet! I'll try and get a review of your changes in by the end of this week.

**Comment by athaynes** [comment]
@PlagueHO No problem at all. I saw that you transferred your DFS module to the gallery so now I am jealous ;)

**Comment by PlagueHO** [comment]
@athaynes - It does feel pretty cool I have to admit :smile: It's Friday here today and hopefully I'll get the "pre" review in tomorrow. Although it will still need to be reviewed by the PS team and they're pretty snowed under I think (and module reviewing is definitely is not an easy job).

**Comment by PlagueHO** [comment]
@athaynes - OK, review number 2 (sorry it took so long). I'll just say, if only MS provided an AuditPolicy PowerShell Module :smile: :

1. https://github.com/athaynes/xAuditPolicy/blob/master/xAuditPolicy.psd1#L15 - Change to SemVer (1.0.0.0)

2. I'm not sure if this is strictly required (but I did it for xDFS), but change the Author,Company and Copyright - https://github.com/athaynes/xAuditPolicy/blob/master/xAuditPolicy.psd1#L21
```
# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) 2016 Microsoft Corporation. All rights reserved.'
```

3. Are you able to specify a minimum PS version?
https://github.com/athaynes/xAuditPolicy/blob/master/xAuditPolicy.psd1#L32

4. Set the private data section (https://github.com/athaynes/xAuditPolicy/blob/master/xAuditPolicy.psd1#L90) like this:
```powershell
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @( 'DSC','DesiredStateConfiguration','DSCResourceKit','DSCResource','AuditPolicy' )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerShell/xDFS/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShell/xAuditPolicy'
```
5. Change https://github.com/athaynes/xAuditPolicy/blob/master/appveyor.yml#L9 to:
version: 1.0.{build}.0

6. Remove the # TODO from this line https://github.com/athaynes/xAuditPolicy/blob/master/appveyor.yml#L47

7. Change this line https://github.com/athaynes/xAuditPolicy/blob/master/LICENSE#L3 to:
Copyright (c) 2016 Microsoft Corporation.

8. Remove this line https://github.com/athaynes/xAuditPolicy/blob/master/.gitignore#L2.

9. Change the following lines to not use positional parameters:
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L52
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L60
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L67
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L358

10. It might be helpful in the Helpers.psm1 file to add a brief help block to each helper function with a .synposis describing the function. This probably isn't really necessary, but makes it a little bit easier to review (although your functions are really nice and trim so easy to understand).

11. It seems that this switch block (https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L141) could be replaced with a single line:
```powershell
$ResourceSACLType = $ResourceSACLType.Substring(0,1).ToUpper()+$ResourceSACLType.Substring(1).ToLower()
```
It took me a couple of reads through to figure out the switch block because I couldn't see where $type came from (but then realized what the intent was). Also this block https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L283

12. It isn't clear what Invoke_AuditPol is actually outputting. It seems to be able to output the pure text of returned by the AuditPol.exe command or an error string. But for a calling function it isn't clear which this is. And there isn't a way to return the LASTEXITCODE. Can I suggest this function is changed to output a HASHTABLE containing the following items (or something similar):
```
@{
    Return = $Return
    LastExitCode = $LastExitCode
}

And rather than just push messages into the pipeline when an error occurs it might be better to actually throw a New-TerminatingError and let the LCM handle it (see how terminating errors are thrown in xWebAdministration). E.g. https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/Helper.psm1#L11

Because at the moment it appears the errors are just returned back to the calling functions, but they don't actually check if an error occurs, so seems to just carry on as normal. For example:
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L172


13. These lines:
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L151
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L299
Will most likely have issues with localization.

E.g. in German versions of Windows I presume this strings will be different. 

I completely understand why you've done it though, but I think it might need to be improved.

It looks like this returns a LASTEXITCODE of 1332 if it doesn't exist, so if Invoke_AuditPol also returned an exitcode (as per item 12) then you could check for this exit code instead of looking at the result text.

14. You could change this line https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L289 to:
switch ($true)
So that dullards like me don't search for the source of the $flags variable :smile:

15. You could add an ```[OutputType([...])]``` decoration to the functions that are expected to provide output.

16. I think all three of these lines should throw a fully constructed exception (E.g. https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/Helper.psm1#L11) and let the LCM handle it:
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L67
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L71
https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L75
Otherwise the LCM doesn't actually know an error has occurred and won't report a problem. You'll only see the problem by checking the logs.

17. https://github.com/athaynes/xAuditPolicy/blob/master/DSCResources/Helper.psm1#L421 - It is possible that this will be an issue with non-English localized operating systems, but it probably won't be. Worth keeping in mind and possibly checking. It should be easy enough to confirm and I've asked around.

Ok, I'll take a little break and try and continue a bit later on.

**Comment by athaynes** [comment]
@PlagueHO Thanks for the through review. I am working my way through the list and should be done in the next day or two. I got started with AppVeyor this weekend and everything seems to run fine but the integration tests fail with:
`The PowerShell DSC resource xauditpolicy does not exist at the PowerShell module path nor is it registered as a WMI DSC resource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : DscResourceNotFound
    + PSComputerName        : localhost`

I dug into the DscResource.Tests to get a better understanding of what all is happening here and see the PSModulePath gets updated in Inialize-TestEnvironment, but I can't figure out why the module is not being found. Is this just a noob problem or is there something else that needs to be done for AppVeyor?

Thanks again for the feedback.

**Comment by PlagueHO** [comment]
@athaynes - Oh! I've run into this problem myself. What you need to do is change the AppVeyor build machine to use WMF5 (it defaults to WMF4 only). The newest test templates require WMF5 to execute the integration tests.

All you need to do is add:
```os: WMF 5```
above the version: line in your AppVeyor.yml

See https://github.com/PowerShell/xDFS/blob/dev/appveyor.yml#L4

This information should actually be added to the Test guidelines in the DSCResources. I'll log an issue.

**Comment by athaynes** [comment]
@PlagueHO That was it. Thanks!!

**Comment by kwirkykat** [comment]
@athaynes I just posted a [new guide](https://github.com/PowerShell/DscResources/blob/master/NewResourceModuleSubmissions.md) for submitting a new resource module.

Can you please open a PR to an empty branch in your repo so that reviewers can make comments?

It looks like @PlagueHO already did a review here, and I don't see any red flags right off the bat, so your review from the design team should be pretty quick :+1:

**Comment by athaynes** [comment]
@kwirkykat I think my empty Pull is ready https://github.com/athaynes/AuditPolicyDsc/tree/reviewTarget

**Comment by athaynes** [comment]
@kwirkykat Sorry about that. I setup the new branches and forgot to setup the pull. You should be good now.

**Comment by kwirkykat** [comment]
Module submission progess:
- [x] 1. Separate public repository created
- [x] 2. Review pull request open
- [ ] 3. 1st reviewer approved (Katie)
- [ ] 4. 2nd reviewer approved
- [ ] 5. 3rd reviewer approved
- [ ] 6. Tests passing
- [ ] 7. Repository transferred
- [ ] 8. Module released

**Comment by athaynes** [comment]
@kwirkykat I deleted the PR and created a new one https://github.com/athaynes/AuditPolicyDsc/pull/24
My git client was not removing the files from staging, so when I did the "empty" commit, everything came over and that was why no file changes showed up. Everything looks correct now. Sorry for all of the noob issues.

**Comment by pburkholder** [comment]
@kwirkykat Thanks for updating the status. This looks like it'll be useful!

**Comment by athaynes** [comment]
Sent the Transfer to @nanalakshmanan. Thanks to @PlagueHO  for all the help getting started.

**Comment by kwirkykat** [comment]
@athaynes Thank you! Just published 😄 https://www.powershellgallery.com/packages/auditpolicydsc/1.0.0.0

**Comment by PlagueHO** [comment]
Awesome work @athaynes - great to get this resource module into the resource kit!
