### ISSUE TITLE
Include some pointers on learning pester

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResources#91]
Perhaps just this link:
https://github.com/pester/Pester#for-further-learning

**Comment by tysonjhayes** [comment]
:+1: Seems like a good idea to me, it took me a while to get up to speed on how to work with Pester not only for DSC but in general, more guidance seems like a pretty good idea.

@PlagueHO has a [blog post series](https://dscottraynsford.wordpress.com/2015/12/14/creating-professional-dsc-resources-part-1/) on how to work with our stuff specifically, maybe we can link to some of his stuff?

**Comment by PlagueHO** [comment]
Thanks @tysonjhayes :smile: Feel free to snip out and use any of the stuff in my blog series if it helps.

Would this go into the [TestGuidelines.md](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) or [Contributing.md](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md)?

I'd think TestGuidlines.md would be more suited to going into more detail about creating unit/integration tests.

**Comment by athaynes** [comment]
I did a write up that focuses a bit more on the why since there is quite a bit of information on the how. I was going to submit a PR for review, but the only branch I see is Master. Did something change in the doc contribution process for new docs?

**Comment by mbreakey3** [comment]
There's no Dev branch in the DscResources repo, so you can just create a PR to be merged into Master

**Comment by johlju** [comment]
The text in [GettingStartedWithPester](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithPester.md) is awesome! Maybe we should just add the link to [further-reading](https://github.com/pester/Pester#further-reading) in the Pester repo just as @TravisEz13 suggested, because it contains a link to list of a lot of sources with information around Pester. After we done that I suggest we close this issue.
